### ISSUE TITLE
String replacement for downloaded branch/type

### ISSUE THREAD

**Issue by JustPlayerDE** [everyday-as/gmodstore-issues#1000]
## Describe a feature you would like to have added to GmodStore

A string replacement to get the branch the file was downloaded from
Example: `{{ script_version_branch }}`

if user Downloads the "Beta" of an addon it would be replaced with `Beta`

## Related attachments
![image](https://user-images.githubusercontent.com/19864478/110745430-86bac300-823b-11eb-9caf-6d35d36d7011.png)

**Comment by Marcuzz** [comment]
The following is added in the next release:

A string replacement: `{{ script_version_release_type }}`

The values this will return include: 
- stable
- beta
- alpha
- private
- demo
