### ISSUE TITLE
Notify users when their review receives a reply

### ISSUE THREAD

**Issue by TheXnator** [everyday-as/gmodstore-issues#1005]
## Describe a feature you would like to have added to GmodStore

Give users a notification when an addon author/agent replies to their review.

Currently they don't and nobody reads/realises that their reviews have been replied to, so those who create a review without making a ticket don't ever notice the reply and remove their review to make a ticket instead.

**Comment by Marcuzz** [comment]
We actually already have this, but upon further inspection it actually looks like we're trying to notify the user who made the reply, instead of the user who made the review. 🤦

**Comment by Marcuzz** [comment]
Fixed in the next patch.
