### ISSUE TITLE
Sanitization and shipment of C/C++ binary modules.

### ISSUE THREAD

**Issue by SimoneStorai** [everyday-as/gmodstore-issues#1006]
## Describe a feature you would like to have added to GmodStore

I'm aware of the severe implications and pitfalls exposing your customers to unconstrained binary code implies, however the fact advanced technologies - any technology, be it the implementation of engine tackling techniques, academic AI, packet interception (the feature my WIP real time voice manipulator relies on), anything that is unfeasible to do without pure performance or function hooking capabilities - need to rely on those should be addressed.

I'm proposing a C/C++ source control facility to be implemented, even a manual one, in order to pave the way for new interesting addons that would be otherwise constrained by Lua's performance and sandboxing (e.g. the code could be analyzed, compiled and pushed by a trusted curator or staff member, with the addon creator being unable to push updates without going through this strict sanitization process).

**Comment by TheodoorP** [comment]
Sadly enough this won't be feasible in the near future
