### ISSUE TITLE
Moderators : Add 'Mark as Unsupported' to Event Logs

### ISSUE THREAD

**Issue by im-richard** [everyday-as/gmodstore-issues#1008]
## Describe a feature you would like to have added to GmodStore
Add new '**Event Logs**' type -> **Marked as Unsupported**

It would be beneficial for GMS staff to see when an addon's developer has marked an addon as unsupported (and vice versa). Which would help when dealing with site reports related to developer's not responding to addon tickets, and then marking the addon as unsupported to keep from providing support.

**Comment by Marcuzz** [comment]
Done in next version
