### ISSUE TITLE
Append version to addon zip filename

### ISSUE THREAD

**Issue by kanalumaddela** [everyday-as/gmodstore-issues#1009]
## Describe a feature you would like to have added to GmodStore
- append `<version>` to a given `<addon>` zip filename when downloading
- `<addon>-<version>.zip`

## Related attachments

![image](https://user-images.githubusercontent.com/14265751/112767953-7ea6a580-8fe7-11eb-9aa3-7da7d42f4517.png)

**Comment by Marcuzz** [comment]
Done in next version
