### ISSUE TITLE
Not able to create coupons for addons

### ISSUE THREAD

**Issue by Stromic** [everyday-as/gmodstore-issues#1011]
## Expected Behavior
It should create the coupon when the date follows the rules set.

## Actual Behavior
Errors and doesnt allow us adding the coupon.

https://i.imgur.com/xbSWRSD.png

## Steps to Reproduce the Problem

  1. Modify addon
  2. Add coupon
  3. Try and set the date

## Specifications

  - GmodStore version (see footer):v8.5.18
  - Example url: https://www.gmodstore.com/dashboard/addons/addonid/coupons
  - Browser: Firefox
  - Event ID:

**Comment by Marcuzz** [comment]
Fixed in the next patch release
