### ISSUE TITLE
Revoked has the same value than reversed

### ISSUE THREAD

**Issue by Venatuss-S** [everyday-as/gmodstore-issues#1013]
On the purchase information page, the "Revoked" has the same value than "Reversed": 
https://gyazo.com/180265316db5de892cabb3c1895c0ee2

When we refund without revoking, the "refunded" box isn't shown here : 
https://gyazo.com/3fed3a6ff411080664a804894559c36c

**Comment by Marcuzz** [comment]
Fixed in 8.5.21

**Comment by Marcuzz** [comment]
Second thing fixed in 8.5.22, it wasn't actually an issue. Judging from the code it looked like intended behaviour, but I've changed it now.
