### ISSUE TITLE
Being able to send a message to someone you blocked

### ISSUE THREAD

**Issue by DiablosCorp** [everyday-as/gmodstore-issues#1014]
## Expected Behavior
When you block someone, you're not supposed to be able to contact him using the private message system.

## Actual Behavior
If you block someone, you're able to message him but since he is blocked he can't answer you and will receive a "_403 No Permission_" message.

## Steps to Reproduce the Problem

  1.  Block someone
  2.  Message him
  3. Wait for him to never reply because he'll have a 403 No Permission error when trying to reply to you

## Specifications

  - GmodStore version (see footer): v8.5.23
  - Example url: Just happened to me at https://www.gmodstore.com/messages/61852
  - Browser: <>
  - Event ID: <>

**Comment by Marcuzz** [comment]
Fixed in 8.5.24
