### ISSUE TITLE
Total != Sum of Prices

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/gmodstore-issues#1017]
## Expected Behavior
Total and the sum of subtotals are equal.

## Actual Behavior
They're not.

![This broken](https://i.doctor-internet.dev/XMvuH0cfsG0z.png)

## Steps to Reproduce the Problem

  1. Buy 10,000 feature tokens.

## Specifications

  - GmodStore version (see footer): v8.6.4	
  - Example url: https://www.gmodstore.com/shopping-cart
  - Browser: Chrome
  - Event ID:

**Comment by Marcuzz** [comment]
Fixed in 8.6.8
