### ISSUE TITLE
Wrong image url on tickets user-message div 

### ISSUE THREAD

**Issue by b4u7** [everyday-as/gmodstore-issues#1019]
## Expected Behavior
The avatar on the user-message field under the reply section on a ticket should grab the 184x184px version of a user's avatar.
![image](https://user-images.githubusercontent.com/10912932/114859056-242c8800-9de2-11eb-9008-684fc810d3c6.png)

## Actual Behavior
Instead, it grabs the 32x32 avatar version of it.
![image](https://user-images.githubusercontent.com/10912932/114859278-6e156e00-9de2-11eb-847e-70407e46822e.png)

## Steps to Reproduce the Problem

  1. Create a ticket
  2. Access the ticket
  3. Look at your avatar under the reply section

## Specifications

  - GmodStore version (see footer): v8.6.6
  - Example url: https://www.gmodstore.com/help/tickets/view/164228
  - Browser: Firefox
  - Event ID:

**Comment by Marcuzz** [comment]
Fixed in 8.6.7
