### ISSUE TITLE
Show time and date on reputation on profiles

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/gmodstore-issues#1020]
## Describe a feature you would like to have added to GmodStore
https://www.gmodstore.com/users/some_user/reputation

Show time and date for when the reputation was left.

## Related attachments
![billede](https://user-images.githubusercontent.com/4314483/114859614-4971c400-9deb-11eb-9e8f-83b76e825645.png)

**Comment by Marcuzz** [comment]
Done in 8.6.7
