### ISSUE TITLE
Can't update EURO price on addon submission

### ISSUE THREAD

**Issue by naviisml** [everyday-as/gmodstore-issues#1021]
## Expected Behavior
Well, I expected to be able to change from 10 euro to 7.50 euro as someone told me it would be better to lower the price of the addon.

## Actual Behavior
I get a error saying the price override must be at least 4.17?

![Screenshot_2021-04-15_Edit_Police_Modifications_-_A_realistic_way_of_arresting_gmodstore](https://user-images.githubusercontent.com/43450192/114892626-3d96f980-9e0d-11eb-8bf3-b6c686ea5bc6.png)

## Steps to Reproduce the Problem

  1. Go to your addon submission page
  2. Change the price in EURO

## Specifications

  - GmodStore version (see footer):	v8.6.7
  - Example url: https://www.gmodstore.com/dashboard/addons/{ADDON_ID}/edit
  - Browser: Firefox
  - Event ID: none

**Comment by Marcuzz** [comment]
Will be fixed in 8.6.8
