### ISSUE TITLE
500 Error after trying to save basic details on addon submission

### ISSUE THREAD

**Issue by naviisml** [everyday-as/gmodstore-issues#1022]
## Expected Behavior
After editting my addon, having a invalid EURO price gives me a 500 error. Theodoor told me it has nothing to do with the input and therefor I open a new issue :)

## Actual Behavior
After trying to save my new addon details, I get a 500 error

## Steps to Reproduce the Problem

  1. Open Basic Information on your addon
  2. Attempt to change the EURO price
  3. Update your settings

## Specifications

  - GmodStore version (see footer): v8.6.7 
  - Example url: https://www.gmodstore.com/dashboard/addons/{ADDON_ID}/edit
  - Browser: Firefox
  - Event ID: 39e6ea819a3046a99fe8503ada3c18ae

**Comment by Marcuzz** [comment]
Fixed in v8.6.8
