### ISSUE TITLE
Only show event filters for events you actually have.

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/gmodstore-issues#1025]
## Describe a feature you would like to have added to GmodStore
Currently, all event filters will show, even if you have no events of the given filter. Change this so only events you actually have have an option to be filtered.

## Related attachments
![](https://i.doctor-internet.dev/e30rPAgsWLXO.png)

**Comment by Marcuzz** [comment]
This would require inverted indexes. Currently the event log has no concept of 'you' or 'your' events. A query to grab only the event types that 'you' have would be a long running query that would also have to run as a separate query too.

This would essentially double the load time of an already slow page and it's not something we're able to do right now.
