### ISSUE TITLE
Using ID's with URL in version.

### ISSUE THREAD

**Issue by Morgan-Moon** [everyday-as/gmodstore-issues#1028]
## Describe a feature you would like to have added to GmodStore
With the URL you would be able to add a #version-name to the end of the URL to the addon.
Example
https://www.gmodstore.com/market/view/7488/versions#1.1.0-stable
When a user clicks this link and loads the page, that version "1.1.0-stable" gets highlighted.

## Related attachments
![image](https://user-images.githubusercontent.com/43384502/115071691-79ee5680-9eee-11eb-9525-d4d2e21d47a2.png)
![image](https://user-images.githubusercontent.com/43384502/115071877-b9b53e00-9eee-11eb-8d96-25466e30ae84.png)

**Comment by TheodoorP** [comment]
What would your use for this be?

**Comment by Morgan-Moon** [comment]
> 
> 
> What would your use for this be?

Just as a addition to a changelog. Ie:
If someone wants to find out what changed in a certain version(lets say there is a lot of versions for example)
Clicking the link would take you straight to that version.

**Comment by Marcuzz** [comment]
I'm not sure how we'd do this using an anchor tag because the versions page is paginated. If we were to do this I think it would be more of a direct link to a specific version.

**Comment by Marcuzz** [comment]
I've added a separate page to show a specific version, it will be available in 9.1:

![image](https://user-images.githubusercontent.com/3168421/122582207-2e743800-d058-11eb-833b-5ce157781caf.png)
