### ISSUE TITLE
"Add All" button for sales

### ISSUE THREAD

**Issue by TheXnator** [everyday-as/gmodstore-issues#1031]
## Describe a feature you would like to have added to GmodStore

A button to add all addons in a team to a sale automatically (at the base price of the sale) without needing to click through all of them individually.

**Comment by Marcuzz** [comment]
Added this in the next update:

https://user-images.githubusercontent.com/3168421/122552973-4a1b1680-d037-11eb-8adb-6e9713ee2b62.mp4
