### ISSUE TITLE
Confirmation when featuring an addon

### ISSUE THREAD

**Issue by TheXnator** [everyday-as/gmodstore-issues#1032]
## Describe a feature you would like to have added to GmodStore

Confirmation/preview dialogue displaying the addon to feature and the big/small text when using an addon token so that people who aren't that bright don't make mistakes...

**Comment by nykez** [comment]
It would be nice to have a preview of what it will look like on the front-page before pressing the confirmation as well.

**Comment by Marcuzz** [comment]
Alright boys

_cracking fingers_

Let's get to work!

**Comment by Marcuzz** [comment]
How's this? 😄 

![image](https://user-images.githubusercontent.com/3168421/122575437-0cc38280-d051-11eb-8bb5-52ac8ec12514.png)

This way you have to press "Preview" before "Use token" even shows up

**Comment by Marcuzz** [comment]
I'll close this issue for now, if there are any concerns feel free to still reply :)
