### ISSUE TITLE
Sorting by Best Rated Sorts by Number of Reviews,

### ISSUE THREAD

**Issue by reesercollins** [everyday-as/gmodstore-issues#1033]
## Expected Behavior
When sorting by 'Best Rated' in the marketplace, it should sort the addons by their rating, probably through some sort of [Bayesian average](https://fulmicoton.com/posts/bayesian_rating/)

## Actual Behavior
Addons are sorted by number of reviews, leading to behaviour like this: 
![image](https://user-images.githubusercontent.com/10563996/116941462-b4b9f380-ac3d-11eb-8975-01bd04b8ed01.png)

## Steps to Reproduce the Problem
  1. Sort addons by Best Rated

## Specifications

  - GmodStore version (see footer): v8.7.6
  - Example url: https://www.gmodstore.com/market/browse?added=any&sortby=rating
  - Browser: Firefox
  - Event ID: N/A

**Comment by Marcuzz** [comment]
Hi,

It's purely sorting by the wrong column. It should be sorting by the lower bounds which is based on a Wilson score confidence interval for a Bernoulli parameter.

Will fix this right away.
