### ISSUE TITLE
Broken Link on Ticket Quick Reply Creation

### ISSUE THREAD

**Issue by reesercollins** [everyday-as/gmodstore-issues#1035]
## Expected Behavior

This link takes you to https://www.gmodstore.com/help/developers/topics/quickreply-variables
![image](https://user-images.githubusercontent.com/10563996/118341970-58818a00-b4ef-11eb-940b-39268166248d.png)

## Actual Behavior

The link tries taking you to https://www.gmodstore.com/help/developers/quickreply-variables

## Steps to Reproduce the Problem

  1. Go to create quick reply on addon
  2. Try clicking on link for quick reply variables

## Specifications

  - GmodStore version (see footer): 8.7.10
  - Example url: https://www.gmodstore.com/dashboard/addons/7646/quickreplies/create
  - Browser: Firefox
  - Event ID: N/A

**Comment by Marcuzz** [comment]
This is fixed in the next update
