### ISSUE TITLE
Disabled addons can still appear in Featured carousel

### ISSUE THREAD

**Issue by dotCore-off** [everyday-as/gmodstore-issues#1037]
## Expected Behavior
Disabled addons should not appear in the Featured carousel as they aren't supposed to be "viewable" &, more importantly, buyable.
Seems to happen only when addon got disabled by Author, not by Content Curator team.
Also note that this isn't a major bug as I assume that this is pretty rare.

## Actual Behavior
Disabled addons can appear in the Featured carousel.

## Steps to Reproduce the Problem

  1. Go on Gmodstore Home page
  2. Be lucky enough to get this situation happens

## Specifications

  - GmodStore version (see footer): 8.7.10	
  - Example url: [PIXEL Jetskis](https://www.gmodstore.com/featured/781)
  - Screenshots: [Featured Carousel](https://imgur.com/enSRLqJ)
  - Browser: Chrome / Edge

**Comment by Marcuzz** [comment]
This is now fixed in the next update and you're right in assuming this normally doesn't happen :)
