### ISSUE TITLE
Add file extension for .dll to the list

### ISSUE THREAD

**Issue by Leystryku** [everyday-as/gmodstore-issues#1038]
## Describe a feature you would like to have added to GmodStore
I'd like for .dll to get added to the list of files which are looked through for automatic file replacements.
This would allow one to i.e. write {{ user_id }} in a DLL and have it be replaced, then using that information for DRM purposes, leak detection, etc.

**Comment by willox** [comment]
Nooo! You can't just perform string replacements in binary files! That's not how the file format works!

**Comment by Marcuzz** [comment]
I don't think this is something we really should be doing 😅
