### ISSUE TITLE
Last used feature tokens doesn't sort correctly

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/gmodstore-issues#1039]
## Expected Behavior
That it would sort by date. Latest featured addon should be the top.

## Actual Behavior
It doesn't sort by date :(

![billede](https://user-images.githubusercontent.com/4314483/119375460-1f010980-bcbb-11eb-8cc0-04beec8dc38b.png)

## Specifications

  - GmodStore version (see footer): v8.7.10 
  - Example url: https://www.gmodstore.com/dashboard/teams/80/feature-tokens#
  - Browser: Firefox

**Comment by Marcuzz** [comment]
Fixed in the next update :)
