### ISSUE TITLE
Refund/revoke reasons

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#1040]
## Describe a feature you would like to have added to GmodStore

We have recently noticed that a select few creators instantly refund customers and close their support ticket, without saying why. This has caused many customers to come to us and say that they did not want a refund, and they're now worried their issue will never be fixed and they won't get future updates.

## Proposed solution

**Solution 1**

In order to improve the customer experience I'm proposing a solution where refunds would now require a valid reason. There would be a dropdown to select a reason, with the following selectable reasons:

- "The product does not work on the customer's server" -> must include a link to a message, image or a support ticket
- "The customer requested a refund" -> must include a link to a message, image or a support ticket
- "The customer has not downloaded the product yet" -> we will automatically check if the customer has downloaded the product and process the refund immediately if they have not
- "Other" -> must provide a reason in free text of a minimum of x amount of characters

~~In all cases, except in the case where the user has not downloaded the addon the refund request will be flagged for review by a moderator/admin.~~ (**edit after feedback:** only flagged creators should be subject to a review)

**Solution 2**
N/A. I had another idea but I'm still trying to map it.

**Comment by Marcuzz** [comment]
Some concerns that I've received:

- A review of a refund should not be required by default, and only creators that we've flagged should be subject to such refunds reviews.
- Revoking access to an addon that someone has purchased should require a reason too. You should not be able to revoke access without refunding without a valid reason like "The customer leaked the addon"

**Comment by Crap-Head** [comment]
From a site ticket:

- Allow users with revoked access/refund to leave a review on the script. Possibly limited to a certain amount of days after their access is revoked.
- Show revoke reason on such reviews?

Developers can still "report" these reviews via site tickets and then we determine if the review is valid or not.

**Comment by snowkitkat** [comment]
Suggestion:

Allow people to make a `Addon Revoke Appeal`

**Comment by Marcuzz** [comment]
> 
> 
> Suggestion:
> 
> Allow people to make a `Addon Revoke Appeal`

While this would be nice, it's not possible for us to "un-refund" a customer because at the end of the day the product is owned by the creator and not by GmodStore

**Comment by Marcuzz** [comment]
It's no longer possible to randomly refund a user, so this issue is now irrelevant
