### ISSUE TITLE
List Subtitle has hover colour

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/gmodstore-issues#1042]
## Expected Behavior
List Subtitle is treated as List Title, for hover purposes.

## Actual Behavior
Hovering over a subtitle gives a colour change.
![](https://i.doctor-internet.dev/JHI89VWoH1qu.png)

## Steps to Reproduce the Problem

  1. Go to a list with subtitles
  2. Hover over the subtitle.

## Specifications

  - GmodStore version (see footer):	8.7.14
  - Example url: https://www.gmodstore.com/dashboard/addons
  - Browser: Chrome 91.0.4472.77 (Official Build) (64-bit) (cohort: Stable)

**Comment by Marcuzz** [comment]
Fixed in the next update
