### ISSUE TITLE
Front page addon prices mismatch

### ISSUE THREAD

**Issue by Leystryku** [everyday-as/gmodstore-issues#1045]
## Expected Behavior
Addon prices should match everywhere

## Actual Behavior
On the front page addons can have two different prices
![image](https://user-images.githubusercontent.com/6385154/121894504-812fb600-cd1f-11eb-9e08-d3c1c7be6037.png)
![image](https://user-images.githubusercontent.com/6385154/121894576-94428600-cd1f-11eb-875c-0acc3410f14c.png)

## Steps to Reproduce the Problem

  1. Open the front page

## Specifications

  - GmodStore version (see footer): v8.7.15
  - Example URL: https://www.gmodstore.com/
  - Browser: Chrome, latest
  - Event ID: idk

**Comment by Marcuzz** [comment]
Fixed in v8.7.16
