### ISSUE TITLE
Don't forget mod note content after submitting and failing

### ISSUE THREAD

**Issue by TheodoorP** [everyday-as/gmodstore-issues#1047]
## Expected Behavior
Submit a mod note with too many characters and get an error + your old note body.

## Actual Behavior
Submit a mod note with too many characters and get an error but no old note body

## Steps to Reproduce the Problem

  1. Submit mod note with too many characters
  2. See that your big mod note is gone
  3. Cry

## Specifications

  - GmodStore version (see footer): v9.1.0 
  - Example url:
  - Browser:
  - Event ID:

**Comment by Marcuzz** [comment]
Fixed in the next update
