### ISSUE TITLE
Editing  addon Knowledge Bases does not work

### ISSUE THREAD

**Issue by Leystryku** [everyday-as/gmodstore-issues#1053]
## Expected Behavior
I expect to be able to edit my knowledge base

## Actual Behavior
I get a 403 Forbidden when trying to edit it
![image](https://user-images.githubusercontent.com/6385154/123647944-d2b06880-d828-11eb-9dfe-bd4690a0f280.png)

## Steps to Reproduce the Problem

  1. Open my addons knowledge base https://www.gmodstore.com/help/addon/7648/read-this
  2.  Click on a topic
  3.  Try to edit topic by pressing edit button
  4. Get 403ed

## Specifications

  - GmodStore version (see footer):	9.1.0
  - Example URL: https://www.gmodstore.com/help/addon/7648/read-this/topics/i-have-false-detection-help-omg/edit
  - Browser: Google Chrome, latest
  - Event ID: not sure

**Comment by Marcuzz** [comment]
Fixed in the next version
