### ISSUE TITLE
Knowledge Base Topics can not be deleted

### ISSUE THREAD

**Issue by Leystryku** [everyday-as/gmodstore-issues#1061]
## Expected Behavior
I expect to be able to delete topics I create through the knowledge base

## Actual Behavior
There is no way to delete them. I do not see a delete button
![image](https://user-images.githubusercontent.com/6385154/124494243-e45cb780-ddb6-11eb-8dd1-5d0627da0124.png)

## Steps to Reproduce the Problem

  1. Go to a topic you created
  2. Try to find a delete button
  3. Realize there is no delete button
  3. Panicking intensifies

## Specifications

  - GmodStore version (see footer):	9.1.2
  - Example URL: https://www.gmodstore.com/help/addon/7648/read-this/topics/i-want-the-viewangle-detection-please (do not delete this plz)
  - Browser: Google Chrome latest
  - Event ID: none

**Comment by Marcuzz** [comment]
Fixed
