### ISSUE TITLE
When leaving a mod note the content isn't cleared

### ISSUE THREAD

**Issue by TheodoorP** [everyday-as/gmodstore-issues#1065]
### Expected Behavior

When I submit a mod note successfully it clears the input box

### Actual Behavior

The input box still contains the now successfully posted old content.

### Reproduction Steps

```markdown
1. Post a mod note
2. Look at the mod note input field
```

### GmodStore Version

v9.1.13

**Comment by Marcuzz** [comment]
Fixed
