### ISSUE TITLE
Curator comment is a moderator note

### ISSUE THREAD

**Issue by DiablosCorp** [everyday-as/gmodstore-issues#1068]
### Expected Behavior

Moderator notes should be written everywhere when they're related to the mod role

### Actual Behavior

If you go at the event log of a user, you'll see that <MOD NAME> posted a curator comment on <USER NAME>. This is a _moderator note_, not a _curator comment_.

https://www.gmodstore.com/users/hv/events example: "Theodoor posted a curator comment on X"

### Reproduction Steps

```markdown
1. Click on a profile and in the User Log
2. Look for the sentence
```

### Browsers

Everywhere

### Example URL

https://www.gmodstore.com/users/hv/events

### GmodStore Version

V9.1.13

**Comment by Marcuzz** [comment]
Fixed
