### ISSUE TITLE
500 Internal Server Error during Login

### ISSUE THREAD

**Issue by FuzzySlug** [everyday-as/gmodstore-issues#1073]
### Expected Behavior

Clicking sign in through steam and logging in should proceed to gmod store's homepage.

### Actual Behavior

After steam sign-in, redirects to 500 Internal Server Error page on Gmod Store.

### Reproduction Steps

```markdown
1. Click sign in through steam on gmodstore
2. Sign in on the steam website
3. Gmodstore 500 Internal Server Error Page appears
```

### Browsers

Chrome Version 91.0.4472.124 (Official Build) (64-bit)

### Example URL

https://www.gmodstore.com/sessions/login

### GmodStore Version

v9.1.13

### Event ID

2f2fe6bd01b14d76b376de344808dd10

### Additional Information

My account is extremely old but I still have many purchases, a possible database glitch may have corrupted my account.

**Comment by Marcuzz** [comment]
This looks to be fixed now.

One of our servers' IP appeared to be blocked by Steam. I recycled the server and everything seems to work fine now.
