### ISSUE TITLE
Knowledgebase anchor tags for quill headings

### ISSUE THREAD

**Issue by TheodoorP** [everyday-as/gmodstore-issues#1075]
### Feature

Supplying references to statements made in quick replies can often be useful. With knowledgebase articles being up to 10.000 characters, this may make it confusing to a user what exactly is being referenced to in the quick reply.

The current solution is often to make a lot of knowledgebase articles, each with a very small scope. This however ends up quite messy.

A good solution would be adding anchor tags to quill headers. Not only would this solve the issue of a user not being able to find what exactly was being referenced, it would also allow knowledgebase articles to have a broader scope. The end result would be less knowledgebase articles with related content, and bigger overall knowledgebase articles, whilst still retaining an easy way to reference information in them.

**Comment by Marcuzz** [comment]
Done
