### ISSUE TITLE
Searchable quick replies

### ISSUE THREAD

**Issue by TheodoorP** [everyday-as/gmodstore-issues#1076]
### Feature

Quick replies are a great feature to easily answer common problems or questions, sometimes however they may be a bit too great and you end up with too many of them. When actually using quick replies, this could end up with an annoying search for the correct reply.

A nice solution for this would be adding a search bar of sorts to the current dropdown.

**Comment by Marcuzz** [comment]
This could possibly be easily solved by using selectize, which we already have installed

**Comment by Marcuzz** [comment]
They're now searchable
