### ISSUE TITLE
Improve ticket overview for banned users

### ISSUE THREAD

**Issue by TheodoorP** [everyday-as/gmodstore-issues#1078]
### Feature

When a user is appeal banned, they're shown a "view previous appeals" button. This button currently brings you to the GmodStore ticket page, with no parameters. 

As all the appeals have (probably) been closed, the users won't actually see any appeals in the default list.

A good solution to this would be adding an unban appeal type to the filter, and redirecting to this instead of the default parameters. It should also include both open and closed appeals, instead of just open appeals.

As a last addition, users that have only been banned from everything and not from appeals, should also be shown a "view previous appeals" button next to the existing "open an appeal" button.

**Comment by Marcuzz** [comment]
Done
