### ISSUE TITLE
Auto-Closing is broken

### ISSUE THREAD

**Issue by LivacoNew** [everyday-as/gmodstore-issues#1094]
### Expected Behavior

Auto-closing would close a ticket after being enabled and having a time set.

### Actual Behavior

It doesn't.

### Reproduction Steps

```markdown
1. Make a ticket to complain about my bad addons.
2. Don't respond for a few days (I have it set for 2 days)
3. It doesn't close.
4. Cry in the corner.
```

### Browsers

Chrome 92.0.4515.131 (64 Bit)

### Example URL

https://www.gmodstore.com/dashboard/tickets/168743 < Ticket that wasn't closed

### GmodStore Version

v9.3.8

**Comment by LivacoNew** [comment]
Unsure what's changed but this seems to have magically fixed itself, for me at least. 
![Screenshot_20211214-144230_Samsung Internet.jpg](https://user-images.githubusercontent.com/51921257/146019932-301be4e2-4f50-43e0-95ae-8680927607dd.jpg)

**Comment by Marcuzz** [comment]
There appears to have been a commit on the 29th of October about 40 minutes after I re-opened this issue that might've fixed it

**Comment by LivacoNew** [comment]
Once again appears to be broken
![](https://upload.livaco.dev/u/p7nVlEaqGJ.png)
![](https://upload.livaco.dev/u/Yj2JLSGy7f.png)
GMS Version v13.1.6
