### ISSUE TITLE
Empty space with Medium display value

### ISSUE THREAD

**Issue by dotCore-off** [everyday-as/gmodstore-issues#1100]
### Expected Behavior

Addon's cards should fill the whole content that is available when a page reachs its limit _(e.g : 15 or 25 addons)_.

### Actual Behavior

There's an empty space at the bottom right of the list, right above the pagination.

### Reproduction Steps

```markdown
1. Go to Your Purchases
2. Set the Display value as Medium
3. Go at the bottom of the list and notice that there's a missing card on the right

P.S : this require to have at least 1 more addon than the selected addons / page value.
```

### Browsers

Edge 92

### Example URL

https://www.gmodstore.com/users/XXXXX/purchases?sort=purchased&per_page=15&display=medium&query=

### GmodStore Version

V9.3.8

### Additional Information

- Please, note that it also works with 25 addons / page or even 50
- This is only a visual bug as all addons are correctly listed if you go through pages

**Comment by dotCore-off** [comment]
Here's an example showcasing the bug -> [https://i.imgur.com/1srzwYg.png](url)

**Comment by b4u7** [comment]
It's currently impossible to do this. Moreover, addon cards should remain consistent. By stretching them based on available space you're unnecessarily making navigation harder, even if marginally to most people. You're placing more of an emphasis on the addon that is stretched, which is not something we want to do.
