### ISSUE TITLE
Light theme issue with leaving reputation

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/gmodstore-issues#1102]
### Expected Behavior

The button to leave reputation to be visible.

### Actual Behavior

The button is invisible.
![billede](https://user-images.githubusercontent.com/4314483/132098259-4c6a1b10-e067-4f90-8fad-94a09864357c.png)

### Reproduction Steps

```markdown
None
```

**Comment by WilliamVenner** [comment]
i hope they remove the light theme in response to this

**Comment by b4u7** [comment]
Fixed in the next release.
