### ISSUE TITLE
Unable to reply to a review

### ISSUE THREAD

**Issue by TheodoorP** [everyday-as/gmodstore-issues#1104]
### Expected Behavior

The ability to reply to a review

### Actual Behavior

Replying to a review returns a 404

### Reproduction Steps

```markdown
1. Make a review
2. Reply to a review
3. See 404
```

### GmodStore Version

 v10.0.10

### Additional Information

This is probably related to the new IDs

**Comment by Marcuzz** [comment]
Fixed in the next patch
