### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by johngetman** [everyday-as/gmodstore-issues#1106]
### Expected Behavior

Open Addon Edit page

### Actual Behavior

500 Internal Server Error

### Reproduction Steps

```markdown
1.Open "Your Addons"
2.Press to my addon
3.Have bug
```

### Browsers

Yandex Browser

### Example URL

https://www.gmodstore.com/dashboard/addons/simple-farming-cooking-system

### GmodStore Version

v10.0.15

### Event ID

2a749e7973a147ccaee176f04074bc96

**Comment by Marcuzz** [comment]
Hi,

This should now be fixed
