### ISSUE TITLE
Check out button stuck on "Checking out..."

### ISSUE THREAD

**Issue by Lysergicore** [everyday-as/gmodstore-issues#1109]
### Expected Behavior

Not being able to finalise any gmodstore purchase on the check out page. 

### Actual Behavior

The button does not do any actions what so ever. Sometimes this error will appear:

` <
 !
 D
 O
 C
 T
 Y
 P
 E
 h
 t
 m
 l
 >
 <
 !
 -
 -
 [`

### Reproduction Steps

```markdown
1. Trying to purchase scripts.
2.
3.
```

### Browsers

Chrome

### Example URL

https://www.gmodstore.com/shopping-cart

### GmodStore Version

v10.1.1

**Comment by TheodoorP** [comment]
I'm able to confirm that checkout also seems to be having issues for me. A developer will look into this shortly!

**Comment by Marcuzz** [comment]
Hi,

This issue was resolved about 4 hours ago now. Thanks for reporting it 😄
