### ISSUE TITLE
Title being to long in Featured Addons section

### ISSUE THREAD

**Issue by Lythium4848** [everyday-as/gmodstore-issues#1110]
### Expected Behavior

The title would possibly be slightly cut off 
![image](https://user-images.githubusercontent.com/62567544/134774427-0dcf47b2-3ad5-40f7-9468-8c2f46b510dd.png)

### Actual Behavior

The title goes slightly outside of the box 
![image](https://user-images.githubusercontent.com/62567544/134771649-a468bd17-a6e2-47b3-87f8-6019033e45d9.png)

### Reproduction Steps

```markdown
1.wait till craphead features chop shop
2.go to featured addons section
3.see that it needs fixing
```

**Comment by b4u7** [comment]
Fixed in v10.2.11
