### ISSUE TITLE
Matched at invalid datetime in alt checker

### ISSUE THREAD

**Issue by TheodoorP** [everyday-as/gmodstore-issues#1116]
### Expected Behavior

The alt checker shows the datetime that something matched

### Actual Behavior

the alt checker says invalid datetime 

### Reproduction Steps

```markdown
1. Be an alt
2. See error when clicking for modal
3.
```

### Browsers

Firefox 92

### Example URL

https://www.gmodstore.com/users/hv/alts

### GmodStore Version

v10.1.9

**Comment by Marcuzz** [comment]
Fixed in the next patch.
