### ISSUE TITLE
Alert Banner hiding subsections

### ISSUE THREAD

**Issue by Aevoaa** [everyday-as/gmodstore-issues#1118]
### Expected Behavior

Underneath the Gmodstore Logo there should be Tabs to view Versions, Discussions and Announcements

![Screenshot 2021-10-05 025632](https://user-images.githubusercontent.com/63224213/135943938-a614192f-4b41-487a-a77a-ec7d5774b4fa.png)

### Actual Behavior

When an Alert is active (e.g The Notification about delayed payment clearance) The bar is not showing

![WRkUAvG](https://user-images.githubusercontent.com/63224213/135944088-f2b42d88-fa2b-42ff-a511-69bcd97c9577.png)

### Reproduction Steps

```markdown
1. Buy Prometheus Discord Integration :) with a Delayed Payment Method e.g SOFORT
2. Refresh for the Alert to appear
3. Enjoy the privilege of not being able to participate in Discussions or view Announcements
```

### Browsers

Brave Version 1.30.87 Chromium: 94.0.4606.71

### Example URL

All gmodstore resources

### GmodStore Version

v10.1.11

**Comment by TheodoorP** [comment]
Fixed in v10.4.15
