### ISSUE TITLE
Let creators know if a feature token can be used right away before purchase

### ISSUE THREAD

**Issue by LivacoNew** [everyday-as/gmodstore-issues#1123]
### Feature

Bought a feature token to advertise a Halloween sale I had going on, went to use it and... oh...
![](https://upload.livaco.dev/u/Ba07rXWCJu.png)
It would be nice if this information was displayed *before* I waste my money and just have a feature token sitting in my team that I can't use for my wanted purpose now. Guess I'll save it for Christmas ¯\_(ツ)_/¯

**Comment by TheodoorP** [comment]
I added the same message, that is quoted above, on the main feature token page, so that creators can view the current waiting time before purchasing a feature token.

I apologize for the inconvenience.

The update with this change will probably be rolled out today.
