### ISSUE TITLE
Homepage bug (0 online users)

### ISSUE THREAD

**Issue by snoopigmod** [everyday-as/gmodstore-issues#1124]
### Expected Behavior

When you look at the homepage and go down, you will notice it says 0 online users. You click on it and you find 3 pages with online users.

Kind Regards
Snoopi

### Actual Behavior

It works but the counter dosen't work i guess

### Reproduction Steps

```markdown
Idk
```

### Example URL

https://gyazo.com/695150f01042a187a938900d166e858a

### Additional Information

Nothing

**Comment by TheodoorP** [comment]
Fixed in 10.2.17
