### ISSUE TITLE
My purchases are messed up (Minor)

### ISSUE THREAD

**Issue by jeremykral666** [everyday-as/gmodstore-issues#1125]
### Expected Behavior

Whenever I click the purchase button, it should display every single one of my purchases made

### Actual Behavior

Whenever I click the purchase button, most of my purchases are shown. A few duplicates (glorifiedhandcuffs, advanced bullet types) and a few are missing (skeypads, zeros methlab 2).

### Reproduction Steps

```markdown
1. I click the "your purchases" button
2. When I click on page 2, I see my purchase on glorifiedhandcuffs and advanced bullet types
3. When I click on page 3, I see my purchase on glorifiedhandcuffs and advanced bullet types again
4. Throughout all my pages skeypads and zeros methlab 2 is missing
```

### Browsers

Chrome

### Example URL

https://www.gmodstore.com/users/jaypkral/purchases

### GmodStore Version

v10.2.19

**Comment by TheodoorP** [comment]
I've applied a fix and if I'm not mistaken you should now be able to see all your addons once!
