### ISSUE TITLE
Rating field must be filled out twice when creating a review

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#1127]
### Expected Behavior

You shouldn't have to click the stars more than once when creating a review

### Actual Behavior

When you click the stars and fill out the other fields you will be told the "the rating field is required" even if you've already filled it out.

### Reproduction Steps

```markdown
1. Own an addon
2. Create a review
3. Fill out the rating field
4. Fill out the rest of the fields
5. Try to submit the review
6. You will be told that "the rating field is required"
```

### Browsers

N/A

### GmodStore Version

10.2.23

### Event ID

N/A

### Additional Information

**There is a workaround:** It is possible to select a rating again and then submit the review, it will then work.

**Comment by b4u7** [comment]
Fixed in next release.
