### ISSUE TITLE
Tickets section showing addon report tickets and script submission tickets

### ISSUE THREAD

**Issue by JonathanVarild** [everyday-as/gmodstore-issues#1128]
### Expected Behavior

The ticket section should according to @Marcuzz not show addon report tickets (issued by others towards me) and script submission tickets.

### Actual Behavior

The tickets section should only show addon tickets that are from my customers and for me to answer.

### Reproduction Steps

```markdown
1. Enter tickets section as a Content Curator
2. Set filters to view all tickets. (open, closed, etc)
4. What to search for:
    a) Search for "Report on" to see report tickets.
    b) Search for a word in the addon name to see submission tickets. AddonID doesn't seem to work although it is in the ticket name.
```

### Browsers

Safari Version 15.1 (17612.2.9.1.20) (macOS Monterey)

### Example URL

https://www.gmodstore.com/dashboard/tickets

### GmodStore Version

v10.2.23

### Event ID

-

### Additional Information

[Example Image](https://cdn.discordapp.com/attachments/280079217021026314/909859819530358794/unknown.png)

**Comment by Marcuzz** [comment]
Fixed in the next bugfix release
