### ISSUE TITLE
Text on the website being white? idk

### ISSUE THREAD

**Issue by snoopigmod** [everyday-as/gmodstore-issues#1129]
### Expected Behavior

Bottom of home page, there would be that text saying "Request served by: gmodstore-web-7c47754c4" but a part of it is marked white. I don't know if this is only me, but just in case I would like to notify you guys.

### Actual Behavior

Bottom of home page, there would be that text saying "Request served by: gmodstore-web-7c47754c4" but a part of it is marked white. I don't know if this is only me, but just in case I would like to notify you guys.

### Reproduction Steps

```markdown
1.
2.
3.
```

### Browsers

Firefox

### Example URL

https://gyazo.com/09531955d329a856da0858036c7eb230

### GmodStore Version

v10.2.25 

### Event ID

1234

### Additional Information

![09531955d329a856da0858036c7eb230](https://user-images.githubusercontent.com/66169218/142921333-59ca948d-6e31-4cc1-b2fd-6ded8bc0ddf3.png)

**Comment by TheodoorP** [comment]
This is intended behaviour.
