### ISSUE TITLE
Budget only accepts integers??

### ISSUE THREAD

**Issue by BullyHunter32** [everyday-as/gmodstore-issues#1131]
### Expected Behavior

I expect to be able to negotiate for $13.50 instead of $13 😤

### Actual Behavior

![image](https://user-images.githubusercontent.com/60613196/143786575-d0a5b289-9da5-4b7c-980f-e02086021e0f.png)
![image](https://user-images.githubusercontent.com/60613196/143786581-e63f00c4-94f2-4e90-a224-f213e9954a07.png)
![image](https://user-images.githubusercontent.com/60613196/143786582-9f4a5c54-bc18-4c97-9ec5-727219643ee0.png)

### Reproduction Steps

```markdown
1. take job
2. discuss budget
3. try to negotiate for $20.50
```

### Browsers

Chrome

### Example URL

https://www.gmodstore.com/jobmarket/jobs/browse

### GmodStore Version

v10.2.26

**Comment by TheodoorP** [comment]
Fixed in v11.0.0
