### ISSUE TITLE
DRM Revocation check for reviews

### ISSUE THREAD

**Issue by FelixKLG** [everyday-as/gmodstore-issues#1140]
### Feature

For addons which have a DRM, it would be nice if it could send a check to see if the user posting the review is blocked via the DRM.

to stop this from being abused i feel only the SteamID64 should be sent and a true or false boolean returned.

it could be as simple as review hiding so it doesn’t impact the actual stars and users can’t see it.

### Additional Information

This feature is to stop people who have tried to leak the addon / crack the DRM from intentionally harming it’s reputation by posting negative reviews.

**Comment by TheodoorP** [comment]
With #671 I don't see this as a useful addition.
