### ISSUE TITLE
title not showing correct 

### ISSUE THREAD

**Issue by ellemti** [everyday-as/gmodstore-issues#1144]
### Expected Behavior

having different color on the button so it shows a colors

### Actual Behavior

the color of text on the button under the profile picture is the same as the background the is

### Reproduction Steps

```markdown
1. entring profile of any user and looking into a portfolio or steam bubble/button, and the problem will be seeing 
2.
3.
```

### Browsers

chrome

### Example URL

https://www.gmodstore.com/users/ellemti

### GmodStore Version

v10.4.15

### Additional Information

this problem is a color problem on the button's and i think it's showing on the review on the profile to , when i finish a job and enter a customer profile and the bubble informs me that i can review him, the problem accrue there to.

**Comment by TheodoorP** [comment]
Fixed a while ago
