### ISSUE TITLE
Invalid Knowledge Base Hyperlink

### ISSUE THREAD

**Issue by owainjones74** [everyday-as/gmodstore-issues#1150]
### Expected Behavior

That I am taken to https://www.gmodstore.com/help/vat/topics/who-do-we-charge-vat-for

### Actual Behavior

I am instead, taken to https://www.gmodstore.com/help/vat/who-do-we-charge-vat-for

### Reproduction Steps

```markdown
1. Go to https://www.gmodstore.com/help/vat/topics/merchant-of-record
2. Click the "who we charge VAT for" hyperlink.
```

### Browsers

Chrome

### Example URL

https://www.gmodstore.com/help/vat/topics/merchant-of-record

### GmodStore Version

V10.4.17

**Comment by owainjones74** [comment]
It seems to be the same for the "VAT and sales tax away from you" hyperlink aswell. They both seem to be missing the "/topics" part of their routes.

**Comment by TheodoorP** [comment]
Fixed, thanks for the report! :)
