### ISSUE TITLE
Updating a script seems to throw a 524

### ISSUE THREAD

**Issue by owainjones74** [everyday-as/gmodstore-issues#1153]
### Expected Behavior

Updating a script should return me to something like the product page once complete.

### Actual Behavior

Every time I update a script (Only tested with TierPrinters), it times me out and gives me a 524 Error. **HOWEVER**, the update is still processed and pushed. This has happened for the last 3 updates I've done.

### Reproduction Steps

```markdown
1. Complete the update form for Tier Printers
2. Push the update
3. Receive a Error 524
```

### Browsers

Chrome

### Example URL

https://www.gmodstore.com/dashboard/addons/4197/versions/create

### GmodStore Version

v10.4.17

### Event ID

I have a Cloudflare RayID, if that helps? 6e219f7abdef7717

**Comment by owainjones74** [comment]
It's worth noting that I have spoken to others and they do not seem to have this issue.

**Comment by TheodoorP** [comment]
This should already be fixed in the upcoming UUID update (v11). Please let us know once that's released whether this issue still occurs!

**Comment by Crap-Head** [comment]
The UUID seems to have fixed this. At least I updated an addon the other day (Fire System) that used to **always** throw this error at me, but now it's smooth.
