### ISSUE TITLE
long messages to customers in ticket creation displays badly

### ISSUE THREAD

**Issue by LivacoNew** [everyday-as/gmodstore-issues#1154]
### Expected Behavior

When I set my message to customers in my addon's support settings it displays nicely and cleanly.

### Actual Behavior

_**e l o n g a t e d - a d d o n - b o x**_
![](https://cdn.discordapp.com/attachments/588834546762645513/947605609170214912/unknown.png)
After getting my friend to send me the support ticket URL for the addon.

### Reproduction Steps

```markdown
1. create popular addon among the likes of blogs and billys whitelist
2. set a message for customers making a ticket so you don't get dumb shit
3. oh no it doesn't display correctly to a customer 
4. profit
```

### Browsers

Firefox 97

### Example URL

https://www.gmodstore.com/help/tickets/create/addon/yet-another-warning-system-yaws-user-warning-and-punishment-system

### GmodStore Version

v10.4.17

**Comment by Marcuzz** [comment]
Fixed in the next release
