### ISSUE TITLE
System Messages title is just a placeholder on mobile

### ISSUE THREAD

**Issue by LivacoNew** [everyday-as/gmodstore-issues#1155]
### Expected Behavior

For it to appear properly

### Actual Behavior

It didn't
![SmartSelect_20220309-084155_Samsung Internet](https://user-images.githubusercontent.com/51921257/157405225-497165b0-c4b5-4ddf-925b-7df7e28ab427.jpg)

### Reproduction Steps

```markdown
1. Sign In
2. Click on your avatar
3. "menu.systemmessages"
```

### Browsers

Samsung Internet 16.2.1.56 on a Samsung S21

### Example URL

www.gmodstore.com

### GmodStore Version

v10.4.18

### Additional Information

Another "bug", as I was trying to get the screenshot I kept getting immediately redirected to settings cus the menu is too high now, and the button overlaps the avatar. Needs either repositioned or cooldown added to it before activating. 

https://user-images.githubusercontent.com/51921257/157405780-d961b95d-02e8-4d9f-9f8a-66fd008db7c7.mp4

**Comment by Marcuzz** [comment]
I'm removing this link for now as it's moved from the next update anyway.
