### ISSUE TITLE
Submission Dashboard shows full UUID not packed UUID

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/gmodstore-issues#1157]
### Expected Behavior

As title.

### Actual Behavior

As title.

### Reproduction Steps

```markdown
Opened the dashboard.
Clicked a link.
Was redirected from full UUID to packed UUID.
```

### Browsers

Chrome

### Example URL

https://staging.gmodstore.com/moderator/submissions, https://staging.gmodstore.com/moderator/submissions/8d7ff107-a364-4e0d-9997-67d78d99a4f4, https://staging.gmodstore.com/moderator/submissions/jX-xB6NkTg2Zl2fXjZmk9A

### GmodStore Version

11.0.0-beta.5

**Comment by TheodoorP** [comment]
Fixed in beta-8
