### ISSUE TITLE
OpenAPI Schema(?) URL 500's

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/gmodstore-issues#1158]
### Expected Behavior

Shows the schema json.

### Actual Behavior

Error 500

### Reproduction Steps

```markdown
Go to https://staging.gmodstore.com/openapi
```

### Browsers

Chrome

### Example URL

https://staging.gmodstore.com/openapi

### GmodStore Version

11.0.0-beta.5

### Event ID

5c1574d9fb034a379073f6ea7f63ae51

**Comment by TheodoorP** [comment]
Fixed in beta 6
