### ISSUE TITLE
Viewing purchase details 500's.

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/gmodstore-issues#1159]
### Expected Behavior

Allows viewing addon purchase details

### Actual Behavior

Error 500's

### Reproduction Steps

```markdown
Go to addon dashboard.
Go to purchase list.
Click "more info"
```

### Browsers

Chrome

### Example URL

https://staging.gmodstore.com/dashboard/addons/ztOfQDzhSYCJ9ZKNpaYPnw/purchases/9b1ede2d-1218-44ea-bb9f-1db4720c386c

### GmodStore Version

11.0.0-beta.5

### Event ID

618896f14a364867aaf9f5ced15fcb45

**Comment by TheodoorP** [comment]
Fixed in beta-8
