### ISSUE TITLE
Editing an addon tab 500s

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/gmodstore-issues#1160]
### Expected Behavior

Opens the addon tab editing UI.

### Actual Behavior

500

### Reproduction Steps

```markdown
1. Go to addon
2. Go to tabs
3. Click "Edit tab"
```

### Browsers

Chrome

### Example URL

https://staging.gmodstore.com/dashboard/addons/dma5uAe5TJaiPQ-LmPIYiA/tabs/9wZip7zGQJKhcqGdRn2qoA/edit

### GmodStore Version

11.0.0-beta.5

### Event ID

3c2d6677b53b4789aa9cec62e8f04147

### Additional Information

Creating a new tab appears to work.

**Comment by TheodoorP** [comment]
fixed in beta-8
