### ISSUE TITLE
500 on job accept/deny

### ISSUE THREAD

**Issue by FelixKLG** [everyday-as/gmodstore-issues#1161]
### Expected Behavior

The job gets accepted/denied and proceeds as usual

### Actual Behavior

HTTP 500 & job not accepted

### Reproduction Steps

```markdown
1. Create Job
2. Someone Applies
3. Accept/Deny applicant
```

### Browsers

Firefox 98 (MacOS M1)

### Example URL

https://staging.gmodstore.com/jobmarket/jobs/NK97nWzsQVepL7RSkPNXLg/application/ikFMQGTeR_SLqdKVBeHr4w

### GmodStore Version

v11.0.0-beta.5 

### Event ID

975250dfa2ea4f27a27c6cf4ecea70e4

**Comment by TheodoorP** [comment]
Fixed in beta-8
