### ISSUE TITLE
Editing an addon collapsible 500s

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/gmodstore-issues#1162]
### Expected Behavior

Opens the collapsible editing menu.

### Actual Behavior

500s

### Reproduction Steps

```markdown
1. Go to addon
2. Go to collapsibles tab
3. Click edit button.
```

### Browsers

Chrome

### Example URL

https://staging.gmodstore.com/dashboard/addons/dma5uAe5TJaiPQ-LmPIYiA/collapsibles/kTgvcJl-TDuYLde6W76OSw/edit

### GmodStore Version

11.0.0-beta.5

### Event ID

2030009d99ec458dab45ceec3cf89029

### Additional Information

This occurred with a new collapsible, created in the staging environment.

**Comment by TheodoorP** [comment]
Fixed the 500, but now there's a 404 that needs fixing
