### ISSUE TITLE
Addon discussions throw a 403

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#1163]
### Expected Behavior

Should not throw a 403

### Actual Behavior

Throws a 403

### Reproduction Steps

```markdown
1. Be someone who's not an adminstrator
2. Try to view an addon discussion
3. 403
```

### Example URL

https://staging.gmodstore.com/market/view/1LUhw4KyR_2WFOkbdw4Y2A/discussion

### GmodStore Version

v11.0.0-beta.5

**Comment by TheodoorP** [comment]
Fixed in beta-8
