### ISSUE TITLE
Searching for users 500

### ISSUE THREAD

**Issue by FelixKLG** [everyday-as/gmodstore-issues#1164]
### Expected Behavior

The list of users where the conditions of the string at matched

### Actual Behavior

HTTP 500

### Reproduction Steps

```markdown
1. Community Tab
2. Search for 'Doctor'
3. 500
```

### Browsers

Firefox 98 (MacOS M1)

### Example URL

https://staging.gmodstore.com/users/browse?query=Doctor+&sortby=relevance&registered=any

### GmodStore Version

v11.0.0-beta.5 

### Event ID

c948da3e012547d0aa669bd478db4e57

**Comment by Marcuzz** [comment]
Fixed in v11.0.0-beta.14.
