### ISSUE TITLE
Entering a knowledgebase article 404s

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/gmodstore-issues#1165]
### Expected Behavior

Shows the article

### Actual Behavior

404 not founds

### Reproduction Steps

```markdown
1. Go into knowledgebase.
2. Go to category.
3. Go to article.
```

### Browsers

Chrome

### Example URL

https://staging.gmodstore.com/help/addon/dma5uAe5TJaiPQ-LmPIYiA/custom-packages/topics/custom-package-example

### GmodStore Version

11.0.0-beta.5

### Additional Information

This only appears to happen with the given link. L2 plate's knowledge base (https://staging.gmodstore.com/help/addon/ztOfQDzhSYCJ9ZKNpaYPnw) appears to be working fine.

**Comment by TheodoorP** [comment]
Doesn't seem to happen with every knowledgebase

**Comment by Marcuzz** [comment]
@J0sh0nat0r Seems like the HasUuidPrimaryKey::getRouteKey method is the culprit here. The route keys for HelpTopic are slugs and getRouteKey assumes it's a packed uuid.
