### ISSUE TITLE
500 on addon creator grant user access

### ISSUE THREAD

**Issue by FelixKLG** [everyday-as/gmodstore-issues#1169]
### Expected Behavior

user gets access

### Actual Behavior

http 500

### Reproduction Steps

```markdown
1. addon purchases
2. try to gift it
3. http 500
```

### Browsers

Firefox 98 (MacOS M1)

### Example URL

https://staging.gmodstore.com/dashboard/addons/qc_HGUpUR5C854mfvjUi2Q/purchases

### GmodStore Version

v11.0.0-beta.6 

### Event ID

89a0123e087c4658b358a00d8559b9a1

**Comment by TheodoorP** [comment]
fixed in beta-8
