### ISSUE TITLE
500 on knowledgebase create category

### ISSUE THREAD

**Issue by FelixKLG** [everyday-as/gmodstore-issues#1171]
### Expected Behavior

New KB category

### Actual Behavior

500

### Reproduction Steps

```markdown
1. Create Knowledgebase category on your addon
2. Press 'Create Category'
```

### Browsers

Firefox 98 (MacOS M1)

### Example URL

https://staging.gmodstore.com/help/addon/mA9U9tYJTdG4I200tXRetw/create

### GmodStore Version

v11.0.0-beta.6

### Event ID

1efe1e0b74ab46799f043c37c4609301

**Comment by TheodoorP** [comment]
fixed in beta.8
