### ISSUE TITLE
can't add addon requirement

### ISSUE THREAD

**Issue by FelixKLG** [everyday-as/gmodstore-issues#1173]
### Expected Behavior

Addon reuirement to be added.

### Actual Behavior

the requirement is not added. network tab gets a 200 & 302 but nothing is saved

### Reproduction Steps

```markdown
1. attempt to add an addon requirement.
2. press save
3. check addon page
```

### Browsers

Firefox 98 (MacOS M1)

### Example URL

https://staging.gmodstore.com/dashboard/addons/qc_HGUpUR5C854mfvjUi2Q/requirements

### GmodStore Version

v11.0.0-beta.7

**Comment by TheodoorP** [comment]
fixed in beta-8
