### ISSUE TITLE
Download failes first time

### ISSUE THREAD

**Issue by FelixKLG** [everyday-as/gmodstore-issues#1174]
### Expected Behavior

Addon downloads as a ZIP.

### Actual Behavior

Addon download fails, however it pops up the error message.
https://media.discordapp.net/attachments/280079217021026314/957668035190210571/unknown.png

works fine if you click download another time.

### Reproduction Steps

```markdown
1. Add **new** addon and approve it
2. click download and watch it fail.
3. click download again
```

### Browsers

Firefox 98 (MacOS M1)

### GmodStore Version

v11.0.0-beta.7

### Additional Information

THE ADDON MUST NOT BE DOWNLOADED BEFORE HAND!
MUST BE **NEW**!

**Comment by J0sh0nat0r** [comment]
Fix applied but unable to reproduce, please re-open if still broken.
