### ISSUE TITLE
Staging forum blank / 403 non admins

### ISSUE THREAD

**Issue by FelixKLG** [everyday-as/gmodstore-issues#1175]
### Expected Behavior

The forum works as it does on the normal site.
https://www.gmodstore.com/community/

### Actual Behavior

the page appears to have no posts.
https://media.discordapp.net/attachments/280079217021026314/957668755058589696/unknown.png

also the posts on the side of this image 403 me.

### Reproduction Steps

```markdown
1. Login as non-admin
2. Check forum
3. (optional) click the posts on the side that appear
```

### Browsers

Firefox 98 (MacOS M1)

### Example URL

https://staging.gmodstore.com/community

### GmodStore Version

v11.0.0-beta.7

**Comment by Marcuzz** [comment]
Fixed in v11.0.0-beta.13
