### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Daitrexat** [everyday-as/gmodstore-issues#1180]
### Expected Behavior

The purchase button should be able to let me buy the addon and add it to my cart

### Actual Behavior

The purchase button brings me to a blank page and my cart is missing

### Reproduction Steps

```markdown
1. go to any addon
2. click purchase
3. experience a blank page
```

### Browsers

Chrome Version 100.0.4896.75 64 bit

### Example URL

https://www.gmodstore.com/market/view/anti-crash/purchase

### GmodStore Version

v11.0.1

### Additional Information

Not sure when this will be fixed but I hope soon because were trying to purchase addons for our server

**Comment by Marcuzz** [comment]
Can you try hard-refreshing your browser by clicking ctrl + f5?

Alternatively try to hold shift and press the refresh button on the top left.
