### ISSUE TITLE
Shopping cart

### ISSUE THREAD

**Issue by Daitrexat** [everyday-as/gmodstore-issues#1181]
### Expected Behavior

I should be able to view my shopping cart

### Actual Behavior

I cannot view my shopping cart and I get an error saying Oh no! We can't find your shopping cart.

### Reproduction Steps

```markdown
1. add a random addon to the cart
2. try and go to the cart to purchase
3. receive an error
```

### Browsers

Chrome Version 100.0.4896.75 64 bit

### Example URL

https://www.gmodstore.com/market/view/anti-crash

### GmodStore Version

v11.0.1

**Comment by Marcuzz** [comment]
This is also fixed in 11.0.2, currently releasing that now.

**Comment by Marcuzz** [comment]
11.0.2 is out now, I would appreciate it if you could verify that it's fixed 😄

**Comment by Daitrexat** [comment]
everything seems to be working thank you :)
