### ISSUE TITLE
Ban endpoint authentication doesn't work

### ISSUE THREAD

**Issue by LivacoNew** [everyday-as/gmodstore-issues#1183]
### Expected Behavior

i have a authentication token with user-bans:read ticked.   
i make request to `https://www.gmodstore.com/api/v3/users/{insert random user's id here}/bans`
they're month long addon creation ban from 2010 shows up  
win

### Actual Behavior

i have a authentication token with user-bans:read ticked.   
i make request to `https://www.gmodstore.com/api/v3/users/{insert random user's id here}/bans`
403 - unauthenticated
loss

### Reproduction Steps

```markdown
1. authentication token with user-bans:read ticked.
2. https://www.gmodstore.com/api/v3/users/{insert random user's id here}/bans
3. rejection
```

### Browsers

Request was made with Postman

### Example URL

https://www.gmodstore.com/api/v3/users/e1ac5734-fa1d-42c4-8d00-6f0a842f9373/bans

### GmodStore Version

v11.0.4 / API 3.0.0

### Additional Information

doing this on yourself also doesn't work, making it a double big issue

**Comment by TheodoorP** [comment]
Fixed in next release (v11.0.12)
