### ISSUE TITLE
No description area when apply jobs

### ISSUE THREAD

**Issue by LastPlayerTR** [everyday-as/gmodstore-issues#1184]
### Expected Behavior

Description area seen and put some words on it 

### Actual Behavior

Description area missing

### Reproduction Steps

```markdown
1.Apply job
2.
3.
```

### Browsers

100.0.4896.88 (Official Build) (64-bit) (cohort: Stable)  Desktop

### Example URL

https://www.gmodstore.com/jobmarket/jobs/ZZkvwhkWTveqX22ROenNEg/application/create

### GmodStore Version

v11.0.4

### Additional Information

![image](https://user-images.githubusercontent.com/73468364/163343208-d098726a-03c2-42ee-bc14-f7ebf2b9f512.png)

**Comment by TheodoorP** [comment]
Can you try Ctrl + F5?

**Comment by LastPlayerTR** [comment]
Yep it worked thanks 💯
