### ISSUE TITLE
Category filters on the marketplace do not work and return no results after latest update

### ISSUE THREAD

**Issue by schneidernicholas** [everyday-as/gmodstore-issues#1186]
### Expected Behavior

When clicking a category filter on the marketplace page, it should filter down to the corresponding results of that category.

### Actual Behavior

No results are displayed (empty marketplace results page).

### Reproduction Steps

```markdown
1. Navigate to the marketplace browse page: https://www.gmodstore.com/market/browse
2. Select "Category" popup from the sidebar.
3. Select any category from the list, such as "DarkRP."
4. No results will be displayed on the marketplace browse page after selecting the category.
```

### Browsers

Edge (Chromium) 100.0.1185.39 (arm64)

### Example URL

https://www.gmodstore.com/market/browse

### GmodStore Version

v11.0.11

### Additional Information

Other filters, such as ratings, sales, and price seem to still work fine.

**Comment by TheodoorP** [comment]
Fixed in the next release (v11.0.12)
