### ISSUE TITLE
Unable to enable 2FA

### ISSUE THREAD

**Issue by EstebX** [everyday-as/gmodstore-issues#1187]
### Expected Behavior

Unable to enable 2FA

### Actual Behavior

Unable to enable 2FA

### Reproduction Steps

```markdown
1. Settings
2. Security
3. Enable 2FA
```

### Browsers

Chrome

### Example URL

https://www.gmodstore.com/settings/security

### GmodStore Version

v11.0.11

### Additional Information

Video: https://www.youtube.com/watch?v=w4hYqChF59o&ab_channel=EstebXDev
GmodStore: https://www.gmodstore.com/users/estebxdev

**Comment by Marcuzz** [comment]
Hi,

I just disabled my 2FA in order to enabled it again and it worked fine for me. Can you try hitting ctrl + f5 and try one more time?

**Comment by EstebX** [comment]
I tried but it didn't work but I tried on my Iphone and there was no more problem.

I'll give you the version of my chrome even if there's a good chance that it comes from a slightly broken extension that I must have

Version 100.0.4896.127 (Build officiel) (64 bits)

Thanks for help
