### ISSUE TITLE
Issue with downloading new addons

### ISSUE THREAD

**Issue by Akulla-A** [everyday-as/gmodstore-issues#1188]
### Expected Behavior

The download button download addon

### Actual Behavior

"An error occurred while trying to process your download. This error usually happens when a creator's webhook is failing, please inform the creator or site staff about this error."

But I don't have any webhooks

### Reproduction Steps

```markdown
1. https://www.gmodstore.com/market/view/ahud-a-darkrp-ttt-murder-hud/versions
2. Download the last version
3. This issue only happens with the last version, the old version downloads properly
```

### Browsers

Edge

### Example URL

https://www.gmodstore.com/market/view/ahud-a-darkrp-ttt-murder-hud/

### GmodStore Version

v11.0.13

### Additional Information

This issue doesn't happen if I upload a new version

**Comment by Marcuzz** [comment]
Hi,

It appears you uploaded that version at a time where there was a bug with where files were uploaded.

I've fixed version 1.0.4 for you now.
