### ISSUE TITLE
Don't show ID in wallat transaction

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/gmodstore-issues#1190]
### Expected Behavior

![image](https://user-images.githubusercontent.com/4314483/163720661-31aff103-5067-4d93-9f3c-05bdb53ce4e7.png)

Don't show ID here. It's already shown when you click in on the transaction

### Actual Behavior

x

### Reproduction Steps

```markdown
1.
2.
3.
```

**Comment by TheodoorP** [comment]
Fixed in next release
