### ISSUE TITLE
Recurring feature tokens don't work post uuids

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#1191]
### Expected Behavior

1. Bonus tokens should be given as expected, should no longer use hardcoded permission group ids
2. Discord boost tokens should be given as expected, refactored to use uuid instead of steamid

### Actual Behavior

Neither work as expected. Simply put: nothing happens

### Reproduction Steps

```markdown
1. It's automated, it just doesn't work
```

**Comment by Marcuzz** [comment]
Does this work now @J0sh0nat0r?

**Comment by Crap-Head** [comment]
![image](https://user-images.githubusercontent.com/4314483/170990136-7f34265e-1cdb-497d-93e0-d80bb58e39b6.png)
I received this a couple of days ago @Marcuzz

**Comment by Marcuzz** [comment]
Cool, thanks for saying @Crap-Head 👍
