### ISSUE TITLE
Team sales not showing upcoming sales

### ISSUE THREAD

**Issue by TheodoorP** [everyday-as/gmodstore-issues#1192]
### Expected Behavior

Team sales showing upcoming sales

### Actual Behavior

Team sales showing currently active sales

### Reproduction Steps

```markdown
1. Make a sale
2. Check the upcoming sales page
```

### Example URL

https://www.gmodstore.com/teams/63kfsro5Sle49gCI4f60pg/sales

**Comment by dotCore-off** [comment]
Dupe of #1139, should I close it then?

**Comment by Marcuzz** [comment]
This should be fixed. It works for me locally at least.
