### ISSUE TITLE
Browsing tickets by specific addon is broken

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/gmodstore-issues#1195]
### Expected Behavior

When I go to my tickets https://www.gmodstore.com/dashboard/tickets and choose a specific addon from the dropdown I expect it to only show tickets for the selected addon.

### Actual Behavior

When I select "bitminers" for example it still show tickets for all addons.

### Reproduction Steps

```markdown
1. Go to https://www.gmodstore.com/dashboard/tickets
2. Select any addon from the dropdown box
3. It will not respect your selection
```

**Comment by Marcuzz** [comment]
This will be fixed in v11.1.14.
