### ISSUE TITLE
Wrong addons shown in Upcoming Sales

### ISSUE THREAD

**Issue by dotCore-off** [everyday-as/gmodstore-issues#1197]
### Expected Behavior

Upcoming Sales addons should show the correct list of addons that are affected by sales.

### Actual Behavior

It looks like it shows every addons of the team instead of the accurate list.

![image](https://user-images.githubusercontent.com/64563384/166846431-a8970a09-2b53-4ef4-8361-9a2f021c6d87.png)
![image](https://user-images.githubusercontent.com/64563384/166846477-0cbb93e0-0a76-48f6-b747-872bde262b72.png)

### Reproduction Steps

```markdown
1. Go to a team with ongoing sales
2. Check the affected addons
3. Compare with the ones that are really on sales
```

### Browsers

Firefox 100

### Example URL

https://www.gmodstore.com/teams/dCERRvg6S2uq4sZOptN5-g/sales

### GmodStore Version

v11.1.13

**Comment by Marcuzz** [comment]
This will be fixed in the upcoming release v11.1.14. Thanks for reporting the issue :)
