### ISSUE TITLE
403 No Permission error when I try to unfavorite an addon wishlist

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/gmodstore-issues#1199]
### Expected Behavior

Clicking the heart to unfavorite an addon on the addon page hsould unfavorite it and remove from wishlist.

### Actual Behavior

You can favorite the addon, but once you click it again to unfavorite it it just returns a 403 no permission error.

### Reproduction Steps

```markdown
1. Go to an addon
2. Favorite it
3. Try to unfavorite it and the error will occur
```

### GmodStore Version

v11.1.15

### Additional Information

See site ticket https://www.gmodstore.com/moderator/tickets/hOAykMOnSsmQY42QKUogbw and https://www.gmodstore.com/moderator/tickets/b0h5P-BbRbaC5c2g71WkxA

**Comment by Marcuzz** [comment]
Fixed in v11.1.17
