### ISSUE TITLE
Incorrect sort order for coupons

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/gmodstore-issues#1201]
### Expected Behavior

That they sort by created or expire time.

### Actual Behavior

They are in a random order

### Reproduction Steps

```markdown
1. Go to an addon
2. Go to coupons
3. Sort order is random
```

### Example URL

https://www.gmodstore.com/dashboard/addons/bitminers/coupons

### GmodStore Version

v11.1.17

**Comment by Marcuzz** [comment]
Fixed in the next release
