### ISSUE TITLE
Tickets API

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#1203]
### Feature

There should be an resource endpoint for ticket update/lock/unlock/hide/reply/on-hold.

It should also be possible to get replies and update/delete them just like you can through the UI.

There should also be an index endpoint to get tickets for a team (teams/:id/tickets) or an addon (addons/:id/tickets). Likewise to get your own created tickets (/users/:id/tickets).

### Additional Information

This feature can be used for a lot of cool stuff, like automatic replies based on context.

**Comment by TheodoorP** [comment]
There is now a tickets api :)
