### ISSUE TITLE
Editing budget on a job throws a 500 error

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/gmodstore-issues#1205]
### Expected Behavior

I should be able to edit the budget on my jobs (I guess until someone is approved for it?)

### Actual Behavior

It throws a 500 internal server error.
Event ID: bd529f2c2c59447d86e060eceaff9e2f

### Reproduction Steps

```markdown
1. Make a job
2. Edit bduget
3.
```

### Browsers

Chrome

### GmodStore Version

v11.3.25

### Event ID

bd529f2c2c59447d86e060eceaff9e2f

**Comment by Marcuzz** [comment]
Can't replicate this anymore. I'll assume it's fixed.
