### ISSUE TITLE
500 error when trying to change my currency to Euro's

### ISSUE THREAD

**Issue by GBanoon** [everyday-as/gmodstore-issues#1206]
### Expected Behavior

I want to pay in euros not dollars, so I can also pay with payment methods used in my country and not creditcard.

### Actual Behavior

Immediately throws a 500 error screen at my face

### Reproduction Steps

```markdown
1. Go to settings page
2. Try changing the currency
3. Save it and see the result

I did do it on multiple devices, with the same result on all of them.
```

### Browsers

Chrome

### Example URL

https://www.gmodstore.com/settings

### GmodStore Version

v11.3.25

### Event ID

fe74e30f6c9948b48432280c8f2283b6

**Comment by Marcuzz** [comment]
This has been fixed for quite a while, please tell us if that turns out to not the case :)
