### ISSUE TITLE
500 error when viewing blocks list with GDPR'd users in

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/gmodstore-issues#1211]
### Expected Behavior

That the website would show me a list of those I have blocked https://www.gmodstore.com/users/crap-head/blocks/issued

### Actual Behavior

It throws a 500 error. Assuming it is because I have a user which has been GDPR'd there.

### Reproduction Steps

```markdown
1. https://www.gmodstore.com/users/crap-head/blocks/issued
```

### Event ID

4f25818f56e14445a8085cae96b29470

**Comment by J0sh0nat0r** [comment]
Fixed in v12.0.11
