### ISSUE TITLE
The "sign me out of all devices" button does not work

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/gmodstore-issues#1214]
### Expected Behavior

That it signs me out of all devices.

### Actual Behavior

Explained per the title and these two tickets:
https://www.gmodstore.com/moderator/tickets/EaGOPKTdTVmjQsDAcyYilw
https://www.gmodstore.com/moderator/tickets/9oUhsV2xQZ61HFleOKNnqg

### Reproduction Steps

```markdown
1. Go to your profile
2. Try to sign out of all devices
```

**Comment by J0sh0nat0r** [comment]
Fixed in v12.0.9
