### ISSUE TITLE
Review count doesnt update for addons

### ISSUE THREAD

**Issue by Stromic** [everyday-as/gmodstore-issues#1218]
### Expected Behavior

When you get a review the count should increase.

### Actual Behavior

It doesnt increase, it gives you it for your personal reputation but it doesnt seem to actually increase the number displayed.

https://i.imgur.com/fpYs6F5.png

### Reproduction Steps

```markdown
1.Check review count
2.Get a review
3.See it not increase
```

### Browsers

Firefox

### Example URL

https://www.gmodstore.com/market/view/gprotect-prop-protection

### GmodStore Version

v11.4.3

**Comment by Marcuzz** [comment]
This should now be fixed.
