### ISSUE TITLE
Wallet Activity transition type all is invalid

### ISSUE THREAD

**Issue by b4u7** [everyday-as/gmodstore-issues#1222]
### Expected Behavior

When going to the Wallet Activity, selecting `transaction type: All`, after selecting any other type, should show all of my transactions.

![image](https://user-images.githubusercontent.com/10912932/195330845-46adc919-db1e-4122-8f71-f53a81bb31df.png)

### Actual Behavior

Selecting `transaction type: all`, after selecting another type, shows an error saying: "The selected transaction type is invalid".

![image](https://user-images.githubusercontent.com/10912932/195331009-c5c74a9c-b51b-4815-93cc-930590cc66cb.png)

### Reproduction Steps

```markdown
1. Go to https://www.gmodstore.com/dashboard/wallet/activity
2. Select any transaction type that isn't All
3. Select transaction type All
```

### Browsers

Firefox 106.0b9 (64-bit)

### Example URL

https://www.gmodstore.com/dashboard/wallet/activity?transaction_type=penalization

### GmodStore Version

v11.6.2

**Comment by Marcuzz** [comment]
Fixed in the next release.
