### ISSUE TITLE
Members of team without permission to view purchases get notified for refund requests

### ISSUE THREAD

**Issue by IServerNetworkable** [everyday-as/gmodstore-issues#1223]
### Expected Behavior

it not to notify me

### Actual Behavior

it notifies me

### Reproduction Steps

```markdown
1.join a team
2.dont have permission for purchase
3.do a refund request
```

### Additional Information

I don't think this is intended behavior, it doesn't really make sense to be notified for something you can't control/respond to

**Comment by Marcuzz** [comment]
This will be fixed in the next release. Thank you for reporting it :)
