### ISSUE TITLE
Status and incidents is down 

### ISSUE THREAD

**Issue by ellemti** [everyday-as/gmodstore-issues#1225]
### Expected Behavior

a working web for [Status and incidents](https://status.gmodstore.com/)

### Actual Behavior

the web link takes u to a webpage with domain https://status.gmodstore.com/ and a text say "Service Unavailable"

### Reproduction Steps

```markdown
1. go to the bottom of any page in gmodstore in the footer container
2. click Status and incidents
3.
```

### Browsers

chrome Version 106.0.5249.119

### Example URL

https://status.gmodstore.com/

### GmodStore Version

v11.7.4

**Comment by TheodoorP** [comment]
It's currently working again.
