### ISSUE TITLE
V3 API with SteamID64's

### ISSUE THREAD

**Issue by LivacoNew** [everyday-as/gmodstore-issues#1226]
### Feature

Unless I'm dumb and am missing something, being able to search for a user via their SteamID64 isn't a thing. It HAS to be Gmodstore's UUID, which afaik you can't get via the API.
![](https://upload.livaco.dev/u/9nxcyz6pav.png)
![](https://upload.livaco.dev/u/pHW0BYzQhi.png)
Being able to search using a SteamID is something I need, otherwise I can't use v3 and my use for it gets killed off alongside v2.

**Comment by TheodoorP** [comment]
You can use the list users endpoint with a steamid filter to get a user by steamid64: [https://docs.gmodstore.com/#operation/listUsers](https://docs.gmodstore.com/#operation/listUsers)
