### ISSUE TITLE
I can't gift a addon

### ISSUE THREAD

**Issue by AntyBD** [everyday-as/gmodstore-issues#1227]
### Expected Behavior

I chose a user and expected that the site would let me give a gift to a friend for the new year

### Actual Behavior

I selected a user, but unfortunately the site says that I need to select a user in order to continue, I don’t understand what the problem is

### Reproduction Steps

```markdown
1. Press Gift Button
2. Select User
3. Wow
```

### Browsers

Chrome 91

### Example URL

https://www.gmodstore.com/market/view/billys-keypad-cracker/purchase

### GmodStore Version

v12.2.2

### Event ID

gmodstore-web-00027-deployment-5f6cd864b8-mng7q

### Additional Information

help please...

**Comment by TheodoorP** [comment]
Hey there,

I've looked into your problem and may have found the reason for your problem. You seem to be trying to gift an addon which is marked as DLC (Billy's keypad cracker requires Billy's keypads & keycards to purchase), I assume however your friend does not own Billy's keypads & keycards.

If your friend does however own Billy's keypads & keycards, and you still encounter the issue, would you be able to provide me with a link to their profile? You can send this either here or send me a message on discord (Theodoor#1337).

Regards.
