### ISSUE TITLE
Editing comments on addon discussions is broken

### ISSUE THREAD

**Issue by LivacoNew** [everyday-as/gmodstore-issues#1228]
### Expected Behavior

Editing a comment works

### Actual Behavior

It doesn't lol
I go to edit a comment, and it won't display the previous text on it for a start.
![](https://upload.livaco.dev/u/x06KyTZn1e.png)
![](https://upload.livaco.dev/u/n60fvbCTxy.png)
Typing something in and clicking Update, doesn't change anything, although the timestamp for the edit does appear/update.
![](https://upload.livaco.dev/u/cmLjxgPHIC.png)
![](https://upload.livaco.dev/u/qgDVK5kzcr.png)

### Reproduction Steps

```markdown
1. Post a comment with bad spelling.
2. Try to update it.
3. Skill issue.
```

### Browsers

Firefox 108.0.1 (64-bit)

### Example URL

https://www.gmodstore.com/market/view/yet-another-warning-system-yaws-user-warning-and-punishment-system/discussion

### GmodStore Version

v12.2.2

**Comment by J0sh0nat0r** [comment]
Fixed in v12.2.3
