### ISSUE TITLE
bound_user_id filter on GET coupon endpoint

### ISSUE THREAD

**Issue by FelixKLG** [everyday-as/gmodstore-issues#1229]
### Feature

I would like to be able to filter coupons that are returned from the API by filtering by the user's ID.

### Additional Information

It would look something like

https://gmodstore.com/api/v3/products/6c5e862b-3dcf-4769-aa6b-8a001937c56b/coupons?filter[userId]=[de37018f-b7b0-4055-9fd7-9ec03f3ac899]

**Comment by TheodoorP** [comment]
Just to get some clarification, I assume you're referring to the bound user when trying to filter by userId?

**Comment by FelixKLG** [comment]
Yes.

**Comment by Marcuzz** [comment]
How painful would it be if we renamed the field from `boundUser` to `boundUserId`? When creating a coupon it has always been `boundUserId`, but it appears to have been mistakenly named `boundUser` when listing coupons.

The filter will then be named `filter[boundUserId]`

**Comment by FelixKLG** [comment]
Actually, I just noticed that on API v2 there is a bound_user however, on V3 its only code.

**Comment by Marcuzz** [comment]
There now is a `filter[boundUserId]` parameter.
