### ISSUE TITLE
Videos uploaded as addon media no longer work

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#1230]
### Expected Behavior

Videos should work as expected.

### Actual Behavior

Videos do not work and throw the following CF worker error:

![image](https://user-images.githubusercontent.com/3168421/209802295-10fc4432-c2bb-4b10-9b2a-9db19e111d39.png)

### Reproduction Steps

```markdown
1. Go to https://www.gmodstore.com/market/view/ehud-perfect-ui-solution-for-your-server
2. Scroll all the way to the right in the media
3. The videos are empty transparent squares

Alternatively:
1. Visit this URL: https://media.gmodstore.com/_/script_media/21ff99c8b3bbfa4b2eab3994c0e33679.mp4
```

### Browsers

N/A

### Example URL

https://media.gmodstore.com/_/script_media/21ff99c8b3bbfa4b2eab3994c0e33679.mp4

### GmodStore Version

v12.3.0

### Event ID

N/A

**Comment by TheodoorP** [comment]
This should be working now
