### ISSUE TITLE
Editing replies glitches

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/gmodstore-issues#1232]
### Expected Behavior

That I can freely edit replies, discussions, creator discussions, mod notes, etc

### Actual Behavior

Every time I try to edit them I only get to type one letter and then it un-selects the editor and continues to do so every time I type one letter.

### Reproduction Steps

```markdown
1. Make a reply/mod note
2. Try to edit it
3. It will un-select every time you type one character
```

### Browsers

Chrome

### GmodStore Version

v12.4.1

**Comment by J0sh0nat0r** [comment]
Fixed in v12.4.2
