### ISSUE TITLE
Textboxes not working on website

### ISSUE THREAD

**Issue by LastPlayerTR** [everyday-as/gmodstore-issues#1233]
### Expected Behavior

1. Submit an application / site ticket
2. It should submit ticket

### Actual Behavior

1. Submit an application / site ticket
2.  The description must not be empty

![image](https://user-images.githubusercontent.com/73468364/211198704-2e58b846-28c2-4eea-8ad5-8c84cb7b5e7e.png)
![image](https://user-images.githubusercontent.com/73468364/211198714-44028577-506f-4777-aa38-835dfb0f7835.png)

### Reproduction Steps

```markdown
1. Submit an application / site ticket
```

### Browsers

Mobile / Desktop 

### Example URL

https://www.gmodstore.com/help/tickets?type=all&state=all

### GmodStore Version

v12.5.0

**Comment by TheodoorP** [comment]
Fixed in v1.5.1 (live now)
