### ISSUE TITLE
error making tickets

### ISSUE THREAD

**Issue by lalupaGaming** [everyday-as/gmodstore-issues#1234]
### Expected Behavior

should make a ticket and say nothing is wrong

### Actual Behavior

i try to make a ticket but it doesnt and says  The body must not be empty
even with text inside the box

### Reproduction Steps

```markdown
1.
2.
3.
```

### Browsers

google chrome

### Example URL

everywhere, addon and website tickets 

### GmodStore Version

v12.5.0

**Comment by LastPlayerTR** [comment]
https://github.com/everyday-as/gmodstore-issues/issues/1233

**Comment by TheodoorP** [comment]
Duplicate of #1233
