### ISSUE TITLE
Tickets/user profiles auto-focus on notes/reply field

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/gmodstore-issues#1235]
### Expected Behavior

That whenever I visit a ticket/user profile it will show the page from the top as usual.

### Actual Behavior

When going to any type of ticket it will automatically scroll towards the bottom of the page and auto-focus on the reply field.
The same goes for going to user profiles where it will automatically focus on the moderator notes at the bottom of their profile.

### Reproduction Steps

```markdown
1. Go to any ticket or user profile (as mod)
```

**Comment by TheodoorP** [comment]
Fixed in  v12.5.13
