### ISSUE TITLE
Can't upload media for addon

### ISSUE THREAD

**Issue by Ethrenduil** [everyday-as/gmodstore-issues#1236]
### Expected Behavior

When I upload an image for my addon, it's added to the media part of my addon.

### Actual Behavior

When I upload an image for my addon, I got an error. 

### Reproduction Steps

```markdown
1.I go to the dashboard of my addon.
2.I click on media.
3.I click on add a new media.
4.I add a title.
5.I click on Upload Image.
6.I click on choose image.
7.I choose my image.
8.I click on create.
```

### Browsers

91 - Chrome

### Example URL

https://www.gmodstore.com/dashboard/addons/potion-legacy-realistic-potion-making-addon/media/create

### GmodStore Version

v12.5.13

### Event ID

9e907317d2b6450c94c5165493ccec4e

**Comment by TheodoorP** [comment]
Should be fixed in v12.5.14
