### ISSUE TITLE
Empty PAT list

### ISSUE THREAD

**Issue by hugoheml** [everyday-as/gmodstore-issues#1237]
### Expected Behavior

I can see all my personnal access tokens list and I can do some actions on.

### Actual Behavior

The personal access token table is empty even I generated PATs.

### Reproduction Steps

```markdown
1. Create a PAT
2. Refresh the page (https://www.gmodstore.com/settings/personal-access-tokens)
```

### Browsers

Chrome/109.0.0.0 Safari/537.36

### Example URL

https://www.gmodstore.com/settings/personal-access-tokens

### GmodStore Version

v12.5.13

**Comment by TheodoorP** [comment]
Fixed in next release v12.5.15
