### ISSUE TITLE
Reply/lock and reply/hide no longer works

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/gmodstore-issues#1240]
### Expected Behavior

That it will reply and lock or reply and hide the ticket as desired.

### Actual Behavior

It **only** replies on both options.

### Reproduction Steps

```markdown
1. Write reply
2. Choose either "reply & lock" or "reply & hide"
3. It only replies, no lock or hide.
```

**Comment by J0sh0nat0r** [comment]
Fixed in the next release
