### ISSUE TITLE
View statistics button on token page doesn't do anything

### ISSUE THREAD

**Issue by DanielMatrixSYS** [everyday-as/gmodstore-issues#1241]
### Expected Behavior

To show me statistics

### Actual Behavior

Button doesnt do anything, just click effect once clicked

### Reproduction Steps

```markdown
Click button
```

### Browsers

Firefox latest version

### Example URL

https://www.gmodstore.com/dashboard/teams/xx/feature-tokens

### GmodStore Version

v12.6.0

**Comment by TheodoorP** [comment]
Fixed once 13.0.1 is released
