### ISSUE TITLE
Can't reply to forum posts

### ISSUE THREAD

**Issue by LivacoNew** [everyday-as/gmodstore-issues#1246]
### Expected Behavior

When I click the post reply button it works

### Actual Behavior

Nothing happens. Confirmed to be a site issue from someone else getting the same issue, and not just an issue with me.
https://user-images.githubusercontent.com/51921257/216140900-f7bd4897-279b-46a3-9d68-4ffd2e77712f.mp4

The sentry request is talking about a quill error of some kind so probably a issue with that.
![](https://upload.livaco.dev/u/Y2KqCjMPhc.png)

### Reproduction Steps

```markdown
1. Find a forum post
2. Reply to it
3. nada
```

### Browsers

Firefox 109.0 (64-bit)

### Example URL

https://www.gmodstore.com/community/threads/lCDZPxwqR5OqRTVDPd9sbw/page/1#post-c720f189-6297-41ba-8248-4709a806f66e

### GmodStore Version

v13.1.0 

### Event ID

96acbdf3ac3f43a7aaef1ecee52ce924 (fetched from the JSON response in the sentry request, not the actual website displaying it)

**Comment by TheodoorP** [comment]
Fixed in 13.1.1
