### ISSUE TITLE
Statistics from feature tokens are not shown

### ISSUE THREAD

**Issue by DanielMatrixSYS** [everyday-as/gmodstore-issues#1248]
### Expected Behavior

Statistics shown instead of just "0"

### Actual Behavior

When you click on the "Show statistics" button inside of the feature token page the window with the data is "0", they're all just 0.

### Reproduction Steps

```markdown
Just click show statistics
```

### Browsers

Firefox latest version

### Example URL

https://www.gmodstore.com/dashboard/teams/DDR6PJsaQLOshjIk4VVRJg/feature-tokens

### GmodStore Version

v13.1.6 

### Additional Information

I was writing this on job hours. As you can see, I am a dedicated gmodstore enjoyer **!**

**Comment by TheodoorP** [comment]
Should be fixed in the next release.
