### ISSUE TITLE
Don't personate deleted accounts as "GmodStore"

### ISSUE THREAD

**Issue by MenschlichTv** [everyday-as/gmodstore-issues#1253]
### Expected Behavior

Should be "User" or "Deleted User"

### Actual Behavior

"GmodStore"

### Reproduction Steps

```markdown
1. Go to https://www.gmodstore.com/market/view/xenin-custom-jobs-creator
2. Scroll down the reviews on last page
3. last review is from "GmodStore"
```

### Additional Information

![image](https://user-images.githubusercontent.com/34013112/230361027-eae97398-7b9e-4af5-9100-baa22acc88a9.png)

**Comment by TheodoorP** [comment]
Fixed in next release.
