### ISSUE TITLE
Centre of attention badge is bugged

### ISSUE THREAD

**Issue by Kobralost** [everyday-as/gmodstore-issues#1263]
### Expected Behavior

Have the badge Centre of attention when you received 50 messages

### Actual Behavior

We don't received this badge

### Reproduction Steps

```markdown
1. Had 50 messages received
2. Nothing was gived
```

### Browsers

All

### Example URL

https://www.gmodstore.com/users/kobralost

### GmodStore Version

v14.7.0

**Comment by J0sh0nat0r** [comment]
Fixed in v14.12.0
