### ISSUE TITLE
Indicate if the customer is using an outdated version in the ticket

### ISSUE THREAD

**Issue by Stromic** [everyday-as/gmodstore-issues#1264]
### Feature

I would like to see if the person that made a ticket has downloaded the latest version, i find myself going into purchases and checking if they have the downloaded version for almost every ticket.

This is a great QOL addition, i think most creators can relate to this.

Here is an example of how it can be indicated:
![msedge_KlSlHLlicU](https://github.com/everyday-as/gmodstore-issues/assets/38598074/f43712e5-cbc4-48ba-8e90-a536228f98bd)

**Comment by TheodoorP** [comment]
Related to #977

**Comment by Marcuzz** [comment]
Done in the next release
