### ISSUE TITLE
Review page selection disappears after first interaction

### ISSUE THREAD

**Issue by LivacoNew** [everyday-as/gmodstore-issues#1265]
### Expected Behavior

The review page selector on an addon page stays put.

### Actual Behavior

It leaves to go play some video games after you first use it.

### Reproduction Steps

```markdown
1. Goto https://www.gmodstore.com/market/view/yet-another-warning-system-yaws-user-warning-and-punishment-system#reviews
2. Look at all those fantastic reviews
3. Go to the next page
4. You can't go back.
```

### Browsers

Firefox 115.0.2 (64-bit)

### Example URL

https://www.gmodstore.com/market/view/yet-another-warning-system-yaws-user-warning-and-punishment-system#reviews

### GmodStore Version

v14.9.1

### Additional Information

https://github.com/everyday-as/gmodstore-issues/assets/51921257/0f0135fe-ecfa-45d1-9f2e-a4ad885be73c

**Comment by J0sh0nat0r** [comment]
Fixed in v14.10.0
