### ISSUE TITLE
Can't search messages by SteamID64

### ISSUE THREAD

**Issue by WilliamVenner** [everyday-as/gmodstore-issues#1267]
### Expected Behavior

Messages filtered by SteamID64

### Actual Behavior

500 Internal Server Error

### Reproduction Steps

```markdown
Enter SteamID64 into search bar on messages page
```

### Browsers

Brave

### Example URL

https://www.gmodstore.com/messages?search=76561198173305878&sortby=newest

### GmodStore Version

v14.9.1

**Comment by TheodoorP** [comment]
Seems to be caused by the UUID migration. Current behaviour is that it will search by user id instead of steam id.

**Comment by J0sh0nat0r** [comment]
Fixed in v14.10.0
