### ISSUE TITLE
More info about transaction does not show for gifted addons

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/gmodstore-issues#1270]
### Expected Behavior

As a content creator I would expect the "more info about transaction" button to show up for all purchases of my addons on a users "Purchases" tab.

### Actual Behavior

If an addon was gifted to an individual, the "more info about transaction" button does not appear, while it appears with bought addons.

https://cdn.discordapp.com/attachments/280079217021026314/1136646680918360156/image.png
https://cdn.discordapp.com/attachments/280079217021026314/1136646681287475310/image.png

**Comment by Marcuzz** [comment]
Fixed in the next release
