### ISSUE TITLE
View now button is bug 

### ISSUE THREAD

**Issue by goldendu54** [everyday-as/gmodstore-issues#1273]
### Expected Behavior

that this button redirects me to the addon page 

### Actual Behavior

the button on the "view now" on the featured page :   [](https://i.imgur.com/TQ8jWCU.png )

### Reproduction Steps

```markdown
1. click on the button "view now" 
2. see the result
```

### Browsers

Brave : Version 1.56.20 Chromium: 115.0.5790.171 (Official Build) (64-bit)

### Example URL

https://www.gmodstore.com/

### GmodStore Version

v14.12.3

### Additional Information

[](https://youtu.be/5fuJzaX5R68)

**Comment by J0sh0nat0r** [comment]
Fixed in v14.12.4
