### ISSUE TITLE
Moderators editing bans broken

### ISSUE THREAD

**Issue by zpetty33** [everyday-as/gmodstore-issues#1287]
### Expected Behavior

If I change properties on existing bans, it should change the properties and then the ban should function as normal allowing me to edit it more or remove it. 

### Actual Behavior

When I edit the end date of an existing ban, it throws a 403 error. Upon refreshing the bans, the change seems to have went through, but I can no longer edit or remove that ban, only view it.

### Reproduction Steps

```markdown
1. Edit an existing ban changing the end date.
2. **should error**
3. Now no longer can edit that ban
```

**Comment by Marcuzz** [comment]
Fixed in the next release.
