### ISSUE TITLE
Statistics page is bugged

### ISSUE THREAD

**Issue by Srlion** [everyday-as/gmodstore-issues#1290]
### Expected Behavior

Weekly & monthly earnings are stuck and not updating.

### Actual Behavior

They should update.

### Reproduction Steps

```markdown
1. Open https://www.gmodstore.com/dashboard
2. Read monthly earnings
3. Check https://www.gmodstore.com/dashboard/wallet
4. You find that monthly earnings value is invalid
```

### Browsers

Firefox 121.0 (64-bit)

### Example URL

https://www.gmodstore.com/dashboard

### GmodStore Version

v17.0.14

### Additional Information

It's been stuck since January 2~3

**Comment by Marcuzz** [comment]
This is fixed now, but the "previous" stat will be broken for a month while we gather more statistics. We had to recreate the entire stats table because something seems to have broken when we renamed addon to product.

**Comment by Srlion** [comment]
@Marcuzz Is this related to having higher earnings than last month and it saying "This statistic is down...etc"

**Comment by Marcuzz** [comment]
> @Marcuzz Is this related to having higher earnings than last month and it saying "This statistic is down...etc"

Yes, that's compared to the "previous" statistic

**Comment by Srlion** [comment]
> > @Marcuzz Is this related to having higher earnings than last month and it saying "This statistic is down...etc"
> 
> Yes, that's compared to the "previous" statistic

For me it has the correct previous stats and still saying down even though this month is higher
