### ISSUE TITLE
Unable to change name.

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/gmodstore-issues#1293]
### Expected Behavior

Allowed to change name in profile settings.

### Actual Behavior

Validation.slug

### Reproduction Steps

```markdown
1. Edit name in profile.
```

### Browsers

Chrome, Brave

### Example URL

https://www.gmodstore.com/settings

### GmodStore Version

V17.1.0

**Comment by Marcuzz** [comment]
Fixed in the next release.
