### ISSUE TITLE
Link to submission page from submission ticket

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/gmodstore-issues#1300]
### Feature

Inside the submission ticket it would be nice if there was a quick link to your addon page.

When viewing the submission as a non-curator/mod it looks like this 
![image](https://github.com/everyday-as/gmodstore-issues/assets/4314483/85f8549d-6514-46ff-badf-d757122ec44c)

You then need to navigate to your profile, products and find the addon in order to update/edit it to what the curator wants. A simple link to the addon similar to how it looks for curators/mods would be nice.

**Comment by Marcuzz** [comment]
Done in the next update.
