### ISSUE TITLE
API - Show permissions of key

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#20]
Yes, that's right, an API key API!

We need to know what permissions an API key has before we make any requests to avoid errors.

The API key API would simply take an API key and tell you what permissions it has and who it's owned by.

**Comment by WilliamVenner** [comment]
@Marcuzz Why was this closed?

**Comment by TheodoorP** [comment]
[this](https://github.com/everyday-as/gmodstore-issues-old/issues/29) this was the original issue

**Comment by Marcuzz** [comment]
I don't know, it was closed 2+ years ago

**Comment by WilliamVenner** [comment]
Pls reopen :)

**Comment by WilliamVenner** [comment]
![image](https://user-images.githubusercontent.com/14863743/107442533-23038400-6b2f-11eb-8134-08aa0818345d.png)

**Comment by Marcuzz** [comment]
Done in 8.6
