### ISSUE TITLE
POSTing to /v2/addons/<id>/versions returns 405

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#536]
## Expected Behavior
POSTing to endpoint /v2/addons/\<id>/versions returns HTTP 201 or 4xx dependent on input.

## Actual Behavior
Server returns HTTP 405 Method not allowed.

## Steps to Reproduce the Problem

  1. Create backend to pull new versions from remote server.
  2. Create HTTP POST request to the addon/\<id>/versions endpoint.
  3. Have HTTP 405 returned.

## Specifications

  - GmodStore version (see footer): GMS Version v4.5.18, API Version 2.
  - Example URL: https://api.gmodstore.com/v2/addons/6030/versions
  - Browser: PHP 7.2.10 & Curl 7.58.0 via Httpful 0.2.20 on Ubuntu 18.04.1 LTS.

![Request Header](https://i.gyazo.com/6f7c41d01892cb1e073200e478fc500d.png)
![Response Header](https://i.gyazo.com/3fbd6bdba99c9499b2b8a9117f70574d.png)

**Comment by TheodoorP** [comment]
Fixed in 7.1.8
