### ISSUE TITLE
Delete/edit posts

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#602]
## Describe a feature you would like to have added to GmodStore
Would be cool if we could delete & edit our own replies to script submissions. For example if we want to change something we said. This would work exactly how editing and deleting posts on the forums and in the comments works.

If this is added, I think it should be added for everything in the moderator dashboard, so site tickets, report centre, submissions and ban appeals. It happens that we say something we would like to change or rephrase and this would be nice :)

## Related attachments
None

**Comment by TheodoorP** [comment]
This should only be possible if the reply hasn't been viewed yet.

**Comment by Marcuzz** [comment]
Done
