### ISSUE TITLE
Reuploaded addons steal proper addon slugs

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#621]
## Expected Behavior
For the actual addon to take the slug

## Actual Behavior
The actual addon has a number appended to it, e.g. -1

## Steps to Reproduce the Problem
I don't think this can be reproduced anymore because it took the denied addon in priority before the real one, so if you try and re-submit it wont work, but:
1. Create an addon
2. Create another addon with the same name
3. The second addon takes the "x" name while the first gets "x-1" 

## Specifications
  - GmodStore version (see footer): v5.0.43
  - Example url: https://www.gmodstore.com/market/view/rprint and https://www.gmodstore.com/market/view/rprint-1
  - Browser: Firefox Developer Edition
  - Event ID: N/A

**Comment by TheodoorP** [comment]
Can't reproduce
