### ISSUE TITLE
Having the last version downloaded of a buyer when he's creating a ticket

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#641]
I think it could be interesting to have "X opened this ticket 2 minutes · 0 replies" with the "- version XYZ" information. This way it will avoid us to go on the purchases tab to find him and retrieving the last downloaded version name.... Atleast it will be really useful for a few of us who make update for our script and who want to know what have our buyers when they need help.
Thanks.
Diablos

**Comment by JoshPiper** [comment]
Related: https://github.com/everyday-as/gmodstore-issues/issues/977
Related: https://github.com/everyday-as/gmodstore-issues/issues/1264

**Comment by Marcuzz** [comment]
Done in the next release
