### ISSUE TITLE
Increased statistics string

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#753]
## Expected Behavior
When hovering over a statistic on the Creator Dashboard which has increased, it should be saying "This statistic..." (which it does if the statistic has gone down)

## Actual Behavior
It says "This statistics.."

## Steps to Reproduce the Problem

  1. Hover on statistic that has increased
  2. Be pedantic as hell
  3. Get mad

## Specifications

  - GmodStore version (see footer): 6.0.12
  - Example url: https://www.gmodstore.com/dashboard
  - Browser: Chrome
  - Event ID:

**Comment by TheodoorP** [comment]
Fixed in next release
