### ISSUE TITLE
New reviews aren't added to the review count

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#758]
## Expected Behavior
A new review should be counted

## Actual Behavior
A new review isn't counted

## Steps to Reproduce the Problem
  1. Write a review for an addon you own
  2. Notice that the review count doesn't go up

## Specifications

  - GmodStore version (see footer): V6.0.27
  - Example url: https://www.gmodstore.com/market/view/6326
  - Browser:
  - Event ID:

**Comment by TheodoorP** [comment]
Seems to work now
