### ISSUE TITLE
Some jobs don't show on "Latest jobs"

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#784]
## Expected Behavior
The jobs on latest jobs page should be showing all of the most recent jobs in order

## Actual Behavior
Some jobs don't show up on the latest jobs but do when you hit "see more". There doesn't seem to be anything specific about these jobs which would cause them not to show other than an accept applicant that has not yet started the job (According to Theo).

## Steps to Reproduce the Problem

  1. Go to "Latest jovs"
  2. Take note of the jobs that show
  3. Hit "See more"
  4. Notice that more jobs show

## Specifications

  - GmodStore version (see footer): 6.0.60
  - Example url: https://www.gmodstore.com/jobmarket
  - Browser: Chrome
  - Event ID: N/A

**Comment by TheodoorP** [comment]
Latest jobs doesn't exist anymore
