### ISSUE TITLE
Cash money flow badge is broken

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#788]
## Expected Behavior
Should get it

## Actual Behavior
Don't get it - seriously, all I need is badges :(

## Steps to Reproduce the Problem

  1. Be really good and get addon approved
  2. Sell addon $$$
  3. Don't get the cool badge :(

## Specifications

  - GmodStore version (see footer): 6.0.63
  - Example url: https://www.gmodstore.com/users/thexnator
  - Browser: Chrome
  - Event ID: N/A

**Comment by TheodoorP** [comment]
Merged to #984
