### ISSUE TITLE
Script comment contents

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#790]
## Describe a feature you would like to have added to GmodStore
Given that there is a limit on the size of a comment on a script, it would be useful for users to have one (or both) of two things to prevent issues where users try to post a comment and then lose a massive body of text because it was too long and have to type it all out again.
Having contents of the text box saved when something like this happens would be incredibly useful, as users would just be able to copy out the contents after realising and split the message or trim it down to be the right length.
Alternatively, preventing users from even being able to press the reply button if the body is too large, or just sticking a little red notification above it when they click off from the text box / input text that reaches a length above the limit.

## Related attachments
This is very sad: https://thexnator.dev/u/tPuFBp3bXL.png

**Comment by TheodoorP** [comment]
Fixed with #1046
