### ISSUE TITLE
Can't reply and hide on a hidden ticket

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#794]
## Expected Behavior
When answering a hidden ticket I should be able to reply and hide as simple replying unhides the ticket

## Actual Behavior
I can't reply and hide

## Steps to Reproduce the Problem
  1. Go to a ticket
  2. Hide it
  3. Look at the reply dropdown.

## Specifications

  - GmodStore version (see footer): V6.0.65	
  - Example url:
  - Browser:
  - Event ID:

**Comment by J0sh0nat0r** [comment]
Fixed in 8.2
