### ISSUE TITLE
Dashboard No Permission

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#811]
## Expected Behavior

Be able to access Dashboard when I have made a Job.

## Actual Behavior

I get an access denied error.

## Steps to Reproduce the Problem

  1. Create a Job Post.
  2. Try and goto the Dashboard.
  3. Bam! No Permission.

## Specifications

  - GmodStore version (see footer): v6.0.66	
  - Example url: https://www.gmodstore.com/dashboard/jobs/32341
  - Browser: Chrome
  - Event ID:

**Comment by TheodoorP** [comment]
Fixed
