### ISSUE TITLE
Featured badge broken for team members

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#824]
## Expected Behavior
Featured badge should be applied to all team members when addon is featured

## Actual Behavior
It is only applied to one of the team members

## Steps to Reproduce the Problem

  1. Have team
  2. Feature addon from team
  3. Observe only one user getting the badge

## Specifications

  - GmodStore version (see footer): 6.0.82
  - Example url: https://thexnator.dev/u/MUA2qDrvti.png | https://thexnator.dev/u/o9BAaWl8jE.png | https://cdn.discordapp.com/attachments/280079217021026314/617692378312081408/unknown.png
  - Browser: Chrome
  - Event ID: N/A

**Comment by TheodoorP** [comment]
Merged to #984
