### ISSUE TITLE
Collapsible Quill element

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#844]
## Describe a feature you would like to have added to GmodStore

A collapsible Quill element.

## Related attachments

Example of why this is needed!

![image](/uploads/d388ed732de74a32a461478fcfa3b832/image.png)

This could be contained in a collapsible element where the user can collapse to see the hidden content.

**Comment by TheodoorP** [comment]
We've added collapsibles for addon pages a while ago, those should suffice until we switch out our editor
