### ISSUE TITLE
Not able to upload attachments

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#866]
## Expected Behavior
Expected to able to upload PNG files as attachments on tickets reply

## Actual Behavior
Nothing happens after clicking "reply" with a attachment selected.

## Steps to Reproduce the Problem

  1. Open any support ticket with on one of the addons that you've bought
  2. Select "attachments" on the reply section
  3. Drag n drop a png file in the specified area.
  3. Click reply

## Specifications

  - GmodStore version (see footer):	v6.2.15 
  - Example url: https://www.gmodstore.com/help/tickets/view/137406
  - Browser: Firefox: 73.0.1 (64-bits)
  - Event ID: none   
![image](/uploads/6720186ea59a427b3479bbe16024bcbf/image.png)

**Comment by TheodoorP** [comment]
Seems to have been fixed.
