### ISSUE TITLE
Ablity to translate reviews

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#874]
## Describe a feature you would like to have added to GmodStore
As there are quite a lot of French members on GmodStore, and not all of GmodStores' users understand French, I'd like to see a possibility to translate reviews in English.

Google has an API for translate, which you could use.

## Related attachments
This could be a potential way to implement it.
![image](/uploads/f37712fb2de7f27f6aa96629b90cb762/image.png)

**Comment by TheodoorP** [comment]
Currently you're not supposed to be leaving reviews in any language but English.
