### ISSUE TITLE
Last downloaded and last version information about the purchaser gets deleted alongside the actual addon version

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#879]
## Expected Behavior
Usually you'd want to keep that information about the user downloading a version.

## Actual Behavior
In some cases, like mine I had to delete my previous versions of a script due to a changed webhook address and implementation - Turns out, removing those versions, also removes the information on who has downloaded them. This is very troublesome for many reasons.

My (un)educated guess is that you cascade the removal due to a relationship between the download info version, and the actual addon version being deleted.

## Steps to Reproduce the Problem

  1. Upload a new addon version
  2. Have someone download it
  3. Delete the addon version

## Specifications

  - GmodStore version (see footer): v6.2.22
  - Example url: N/A
  - Browser: Opera 67.0.3575.137
  - Event ID: N/A

**Comment by TheodoorP** [comment]
Fixed in next release.
