### ISSUE TITLE
Turn pagination up to 16 on purchases page.

### ISSUE THREAD

**Issue by FoksVHox** [everyday-as/gmodstore-issues#886]
_DISCLIAMER: I'm not sure if this is a bug or a feature request, please notify me if it is a feature request._

## Expected Behavior
I assume it should show on page with 16 results on one page and then the rest on the second.
It would also remove the awkward white space there is when the pagination is there
![image](https://user-images.githubusercontent.com/37844753/80915294-aa76c800-8d51-11ea-8bf9-da7b5f7199df.png)

## Actual Behavior
If a user has more than 16 purchases the page will make pagination with 15 results on page one, and one on the second page.

## Steps to Reproduce the Problem

  1. Find a user that has more than 16 purchases
  2. Click on purchases in the navbar.
  3. Scroll down to the pagination

## Specifications

  - GmodStore version (see footer): 6.2.36
  - Example url: https://www.gmodstore.com/users/dan/purchases
  - Browser: Brave

**Comment by Marcuzz** [comment]
The main problem with these numbers is the fact you can swap the layout of the grid, and that changes how many are shown on the same row.

That means that on the small display type "16" would no longer work. Changing the amounts based on what grid display you've chosen is an option, but that is rather annoying as we'd have to 'patch' the query string whenever someone swaps grid display.

**Comment by FoksVHox** [comment]
Isn't there any other way of fixing this? I know it isn't the biggest issue in the world but it just feels awkward :/

**Comment by OwjoTheGreat** [comment]
Could you not make the default display setting "Small", that way by default it fits?

I also personally prefer this setting as banners fit correctly etc.

**Comment by Marcuzz** [comment]
The default will be 'small' in the next update.
