### ISSUE TITLE
Unable to view some support tickets

### ISSUE THREAD

**Issue by TheodoorP** [everyday-as/gmodstore-issues#892]
## Expected Behavior
Be able to view a support ticket.

## Actual Behavior
Some support tickets seem to throw 500s for no apparent reason, two examples:

- https://www.gmodstore.com/dashboard/tickets/138283
- https://www.gmodstore.com/dashboard/tickets/141560

## Steps to Reproduce the Problem

  1. Open the ticket
  2. Get a 500

## Specifications

  - GmodStore version (see footer): v7.0.0-alpha.38
  - Example url: see body
  - Browser: 
  - Event ID:

**Comment by Marcuzz** [comment]
This appears to be fixed
