### ISSUE TITLE
Users can see deleted threads

### ISSUE THREAD

**Issue by TheodoorP** [everyday-as/gmodstore-issues#893]
## Expected Behavior
A thread to be hidden from normal users when it has been deleted

## Actual Behavior
The thread is still visible on the forum, however once clicked on it throws a 403

## Steps to Reproduce the Problem
  1. Lock thread
  2. Look at forums as non-admin user

## Specifications

  - GmodStore version (see footer):	v7.0.9
  - Example url: https://www.gmodstore.com/community/threads/6639
  - Browser:
  - Event ID:

**Comment by Marcuzz** [comment]
Fixed in the next release
