### ISSUE TITLE
Footer Links Casing

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/gmodstore-issues#894]
## Expected Behavior
"Issue Tracker" & "Status and Incidents" links on the footer should be in Title Case, as with the other footer links.

## Actual Behavior
They're written "Issue tracker" and "Status and incidents".

## Steps to Reproduce the Problem

  1. Go to footer.

## Specifications

  - GmodStore version (see footer): v7.0.14	
  - Example url: https://www.gmodstore.com/jobmarket
  - Browser: Chrome 81.0.4044.138 (Official Build) (64-bit) (cohort: Stable)

**Comment by JoshPiper** [comment]
Also appears to be an issue on the navbar, "Creator dashboard" vs "About Us"

**Comment by Marcuzz** [comment]
Fixed
