### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by SH-Esteb** [everyday-as/gmodstore-issues#896]
Like that (Browser notifications)

CLIENTS : 
$Developper has just updated its addons $Addons.
You get a new answer on your ticket with $Developper.
Your ticket has been closed by $Developper.

DEVELOPERS : 

Your addons have not been accepted.
Your addons have been accepted!
You have a new ticket!
Your payment has been made!

**Comment by Marcuzz** [comment]
Hi,

Do you mean push notifications? You can already enable those [here](https://www.gmodstore.com/notifications)

**Comment by SH-Esteb** [comment]
Currently I'm ban: 'but something like that
![image](https://user-images.githubusercontent.com/55597307/82681772-8ae70700-9c4e-11ea-9e6b-dc20db17cdaa.png)

**Comment by Marcuzz** [comment]
Yeah, we already have this :)
