### ISSUE TITLE
Subscribe system with notifications (content creators)

### ISSUE THREAD

**Issue by ZJK57** [everyday-as/gmodstore-issues#898]
## Describe a feature you would like to have added to GmodStore

Hey, I had a pretty cool suggestion in mind for a couple time already;
As a big and recurent buyer myself, I'd like to know whenever a content creator posts a new addon on the GMS (gets accepted)

So what about a subscribe system that would send a notification same as the default ones when a new addon is available from the subscribed author ?

I don't know if it has been suggested already, but it would be really cool to see this small feature here, thanks !

## Related attachments

Profile:
![idea gms](https://user-images.githubusercontent.com/35749378/82741841-cd940680-9d56-11ea-9dcc-4dd1214e08fe.png)

Notifications:
![idea gms2](https://user-images.githubusercontent.com/35749378/82741912-c6b9c380-9d57-11ea-8578-17acaca12c5a.png)

**Comment by BullyHunter32** [comment]
This is a cool idea, perhaps "Follow" would be a better word for it

**Comment by ZJK57** [comment]
> This is a cool idea, perhaps "Follow" would be a better word for it

Yea I was thinking about it, definitely better
