### ISSUE TITLE
API return 500 when key don't have access to addon

### ISSUE THREAD

**Issue by FoksVHox** [everyday-as/gmodstore-issues#900]
## Expected Behavior
It should return something else than a 500, most likely an error message.

## Actual Behavior
It returns a 500 message.

Example: 
![image](https://user-images.githubusercontent.com/37844753/83801037-b9320100-a6a8-11ea-8905-6f19b1b24277.png)

## Steps to Reproduce the Problem

  1. Create an API key that has `Read addon versions` permission
  2. Test the API with an addon that you don't own
  3. See 500 error

## Specifications

  - GmodStore version: v7.0.29
  - Example URL: https://api.gmodstore.com/v2/addons/6318/versions
  - Browser: It is the HTTP library in Laravel.
  - Event ID: N/A

**Comment by FoksVHox** [comment]
And yes, I've removed the API key in the picture.

**Comment by TheodoorP** [comment]
API returns 403 now.
