### ISSUE TITLE
Make the open tickets decrease a positive decrease

### ISSUE THREAD

**Issue by GlorifiedPig** [everyday-as/gmodstore-issues#901]
At the moment, the "open tickets" statistic on your dashboard is red when it's lower since the previous month. Make it green instead of red. QoL suggestion - https://cdn.discordapp.com/attachments/280079217021026314/719506028068339742/unknown.png

**Comment by FoksVHox** [comment]
Yes! Right now it seems like GMS want us to have more ticket each month

**Comment by Marcuzz** [comment]
Done in the next update
