### ISSUE TITLE
Budget Search is broken

### ISSUE THREAD

**Issue by FoksVHox** [everyday-as/gmodstore-issues#903]
## Expected Behavior
When I go to the browse jobs and want to search for jobs with a minimum number as a budget I should get the jobs with at least the amount as a budget

## Actual Behavior
I don't get the jobs, but an error saying that the number isn't a number

## Steps to Reproduce the Problem

  1. Go to the browse jobs tab on GMS
  2. Enter a minimum number in the budget search
  3. Get the error

## Specifications

  - GmodStore version (see footer): 7.0.38
  - Example URL: https://www.gmodstore.com/jobmarket/jobs/browse
  - Browser: Brave (Chrome based)
  - Event ID: *None*

**Comment by Marcuzz** [comment]
This should be fixed now
