### ISSUE TITLE
Gmodstore Leaderboard

### ISSUE THREAD

**Issue by snoopigmod** [everyday-as/gmodstore-issues#904]
**Gmodstore Leaderboard**

The Leaderboard could for an example show top 20 addon creators or top 20 of money gathered of creator like:

Total sold for.....

DanFMN - 30000 dollars
Sleeeppyyy - 10000 dollars

Something like that.

Thank you 
Snoopi - https://www.gmodstore.com/users/76561198157042191

**Comment by FoksVHox** [comment]
But why?

**Comment by TheodoorP** [comment]
Showcasing users isn't something we deem necessary. We've already got the popular addons section to showcase "popular" addons and have given users the ability to sort addons by "Best seller" and "Best rated" in the marketplace. Our site is all about showcasing addons, not the users that create them.
