### ISSUE TITLE
Temporarily banned users to be able to view own addons

### ISSUE THREAD

**Issue by NoSharp** [everyday-as/gmodstore-issues#905]
## Describe a feature you would like to have added to GmodStore
Temporarily banned users should be able to view and offer support for and update their own addons.

**Comment by TheodoorP** [comment]
We don't fully ban users from accessing the site unless we deem it necessary. If you get a full ban for whatever reason accessing support tickets is not something you're supposed to be doing. Temporary full bans are a time-out.
