### ISSUE TITLE
Automatically disable unsupported addons that haven't been downloaded for over 3 months

### ISSUE THREAD

**Issue by TheodoorP** [everyday-as/gmodstore-issues#908]
## Describe a feature you would like to have added to GmodStore
Currently, we've got quite a few potentially broken and unsupported addons on the marketplace. Automatically disabling these should stop customers from buying these and coming to the discovery that they're broken.

If an author wants the addon to be re-enabled for whatever reason they can go ahead and open a site ticket. After which a moderator can download the addon, test it and if it works re-enable the addon for another 3 or more months (depending on whether the addon actually gets downloaded in that timeframe).

**Comment by Marcuzz** [comment]
The final parameters for this are (inclusive of each other):

- No new version in one year
- No downloads in the past 6 months
- No purchases in the past 6 months
