### ISSUE TITLE
Prevent blocked users commenting on scripts

### ISSUE THREAD

**Issue by TheXnator** [everyday-as/gmodstore-issues#912]
## Describe a feature you would like to have added to GmodStore
Don't let blocked users comment on scripts of people they are blocked why, would prevent people who like to go on literally any script that someone has made and shit on them religiously

**Comment by TheodoorP** [comment]
Not something we will be adding, we want users to be able to out their opinion on an addon, whether they're blocked or not. If a user comes by and "shits" on a script with no actual grounds please open a site ticket, we will deal with them accordingly.
