### ISSUE TITLE
Pagination allows you to go under 1 & 0

### ISSUE THREAD

**Issue by FoksVHox** [everyday-as/gmodstore-issues#914]
## Expected Behavior
I would expect the pagination stopping you from going below 1 or 0, but it doesn't'

## Actual Behavior
The pagination buttons let you go under 1 and 0

## Steps to Reproduce the Problem

  1. Go to an addon with multiple pages
  2. Go to the last page using the pagination buttons
  3. Then go to the first page using the pagination buttons
  4. Then press the back pagination button again when the page is on 1

## Specifications

  - GmodStore version (see footer): v7.1.7
  - Example URL: https://www.gmodstore.com/market/view/skeypads
  - Browser: Brave
  - Event ID: N/A

**Comment by Marcuzz** [comment]
Fixed in the next milestone
