### ISSUE TITLE
You're not able to click answer the "Is this helpful to you?" on different reviews

### ISSUE THREAD

**Issue by FoksVHox** [everyday-as/gmodstore-issues#915]
## Expected Behavior
I'd expect the "Is this helpful to you?" to allow you to press "Yes" on different reviews once you have press "Yes" on one review...

## Actual Behavior
You aren't able to press "Yes" on different reviews once you have press "Yes" on one

## Steps to Reproduce the Problem

  1. Go to an addon with multiple reviews
  2. Press "Yes" to the "Is this helpful to you?" on a review, it doesn't matter which one you take
  3. Find another review and try to press the "Yes", which it doesn't

## Specifications

  - GmodStore version (see footer): v7.1.7
  - Example URL: https://www.gmodstore.com/market/view/skeypads
  - Browser: Brave
  - Event ID: N/A

**Comment by Marcuzz** [comment]
Fixed in the next milestone
