### ISSUE TITLE
Problem with the version system 

### ISSUE THREAD

**Issue by Kobralost** [everyday-as/gmodstore-issues#916]
## Expected Behavior
Can add a new version of my addon 

## Actual Behavior
I can't add a new version of my addon 

## Steps to Reproduce the Problem

  1. Upload a new version of an addon 

## Specifications

  - GmodStore version (see footer): v7.1.8	
  - Example url: https://www.gmodstore.com/dashboard/addons/7060/versions
  - Browser: Google Chrome
  - Event ID: 8ecfa7ff21d44b7b995a760d4ed85163

**Comment by TheodoorP** [comment]
Fixed in 7.1.9
