### ISSUE TITLE
Badge: Downloader ("Downloaded over 50 different addons") possibly not being awarded

### ISSUE THREAD

**Issue by im-richard** [everyday-as/gmodstore-issues#918]
## Expected Behavior
When a user downloads over 50 different addons, they should be awarded with a badge that displays on their profile page.

## Actual Behavior
User has reported that badge currently not being given.

## Steps to Reproduce the Problem

  1. Download over 50 different addons

## Notes
Checked with user to see when the badge would have been given to avoid the possibility of cache being the reason. User passed the mark well over a month ago and doesn't have badge listed on profile.

## Specifications

  - GmodStore version (see footer): v7.1.10
  - Example url: https://www.gmodstore.com/users/76561198143613461

**Comment by J0sh0nat0r** [comment]
Fixed in 8.2
