### ISSUE TITLE
Gif Banners

### ISSUE THREAD

**Issue by Matrix324** [everyday-as/gmodstore-issues#919]
## Describe a feature you would like to have added to GmodStore
It'd be nice to have the ability to have a gif as your banner for your addons and to avoid the site from getting messy with gifs playing all the time I'd like to suggest that the gifs on ly play when you hover over them.

## Related attachments
None

**Comment by TheodoorP** [comment]
We're not interested in adding this feature.

**Comment by FoksVHox** [comment]
@TheodoorP Is there a reason to it?

**Comment by Marcuzz** [comment]
Well, for one, we just don't want this feature on our marketplace. We're also not interested in people inevitably abusing it even if it's just 'on hover'. I'm sure people will put some sort of ads in there.

Another thing is we can't just "play a gif on hover", it's more complicated than that. We'd need to create a snapshot of the first frame of a gif and load that first, as just a normal image. Then, on hover, we'd need to replace the static image with a gif. I just don't see the time spent doing this being worth it at all, which means it would lay here in the backlog forever as no-one wants to touch it.
