### ISSUE TITLE
display_order in permission-groups API is nullable

### ISSUE THREAD

**Issue by TheodoorP** [everyday-as/gmodstore-issues#926]
## Expected Behavior
display_order shouldn't be nullable

## Actual Behavior
display_order is nullable

## Steps to Reproduce the Problem

  1. Create a new group
  2. Don't move it
  3. Check the permission-groups API

## Specifications

  - GmodStore version (see footer): v7.1.24
  - Example url:
  - Browser:
  - Event ID:

**Comment by Marcuzz** [comment]
Fixed in the next milestone
