### ISSUE TITLE
API Endpoint getUser does not return reputation & team_reputation despite being in docs

### ISSUE THREAD

**Issue by Alydus** [everyday-as/gmodstore-issues#927]
## Expected Behavior

The API Endpoint getUser, known as 'Fetch a single user' in the docs (https://docs.gmodstore.com/#operation/getUser) should return two keys under data, 'reputation' and 'team_reputation'.

## Actual Behavior

After testing this endpoint with multiple user ids, these keys are not returned.

## Steps to Reproduce the Problem

  1. Using your API key, send a GET request to this endpoint
  2. Use the user id of '76561198075511009' (myself)
  3. There is no reputation or team_reputation keys.

## Specifications

  - GmodStore version (see footer): No versioning in docs, but main site shows v7.1.26
  - Example url: https://api.gmodstore.com/v2/users/76561198075511009?api_key=YOURKEY
  - Browser: Google Chrome Version 85.0.4183.102 (Official Build) (64-bit)
  - Event ID: N/A

**Comment by Marcuzz** [comment]
There you go, fixed!
