### ISSUE TITLE
Webhook when a customer gets banned

### ISSUE THREAD

**Issue by PatrickRatzow** [everyday-as/gmodstore-issues#931]
## Describe a feature you would like to have added to GmodStore
A webhook that would be fired when a customer for any of your scripts gets banned.

Instead of having to occasionally pull customers banned status, this would make it possible to always have up to date information about a customers ban status.

**Comment by PatrickRatzow** [comment]
Duplicate of [https://github.com/everyday-as/gmodstore-issues/issues/913](https://github.com/everyday-as/gmodstore-issues/issues/913 )

**Comment by TheodoorP** [comment]
Duplicate of #913
