### ISSUE TITLE
Addon count on user's profile includes non-public addons.

### ISSUE THREAD

**Issue by phixmeplease** [everyday-as/gmodstore-issues#937]
## Expected Behavior
When viewing the addon count on the reputation panel for a user, you expect it to only count public addons.

## Actual Behavior
The addon count on the reputation panel for a used counts all un-released and all un-submitted addons.

## Steps to Reproduce the Problem

  1. Go to anyone's profile who has un-released addons. Stromic's profile is a good example.
  2. Look at the reputation panel, remember the addon count it says
  3. Compare it to the addons tab.

## Specifications

  - GmodStore version (see footer): v7.1.40
  - Example url: https://www.gmodstore.com/users/76561198387898442
  - Browser: ALL
  - Event ID: idk what this is, pretty strait forward bug report

**Comment by phixmeplease** [comment]
NOTE: It appears stromic's profile no longer has this issue, you will need to look for another profile. Owain has a whole team of un-released addons. Might want to check there.

**Comment by TheodoorP** [comment]
Can't currently replicate this on Owain's and Stromic's profile
