### ISSUE TITLE
Revert to 2018 UI

### ISSUE THREAD

**Issue by phixmeplease** [everyday-as/gmodstore-issues#939]
## Describe a feature you would like to have added to GmodStore
I recently took a look at some old dev blogs, and I saw one post (https://www.gmodstore.com/community/threads/5400) detailing the new UI. I saw this and I thought it looked better then the current UI. I like the black touches everywhere and the rounded buttons. Most people prob wont agree, but I think this UI would look better on the website then the current one. The current one has too much color in my opinion.

**Comment by phixmeplease** [comment]
p.s. I like the new home page, cleaner then the old one, the main thing is rounded buttons Xd

**Comment by TheodoorP** [comment]
We're not planning on reverting back to circles.
