### ISSUE TITLE
Extra underlined space on names in Addon Discussions 

### ISSUE THREAD

**Issue by JustPlayerDE** [everyday-as/gmodstore-issues#940]
## Expected Behavior
![image](https://user-images.githubusercontent.com/19864478/97080037-cbc9ba00-15f8-11eb-99fe-b21d4118449e.png)

A Nice underlined name without extra space

## Actual Behavior
![image](https://user-images.githubusercontent.com/19864478/97080031-bb194400-15f8-11eb-8a76-107ee85ec7a1.png)

A underlined name with extra underlined space

## Steps to Reproduce the Problem

  1. Hover over a User in the Discussions tab of an addon

## Specifications

  - GmodStore version (see footer): v7.1.40
  - Example url: https://www.gmodstore.com/market/view/7359/discussion
  - Browser: Google Chrome 86.0.4240.111 (64-Bit)
  - Event ID: None

**Comment by b4u7** [comment]
Fixed in beta-19
