### ISSUE TITLE
Popular Addons Discount on width<1080px

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/gmodstore-issues#942]
## Expected Behavior
Elements are re-sized or moved to remain inside the addon box.

## Actual Behavior
Price box pops out of the side of the addon box.
![image](https://user-images.githubusercontent.com/32164094/98939634-a3d7c300-24e1-11eb-83ab-06681d6dceed.png)

## Steps to Reproduce the Problem

  1. Have a 1080px wide browser window
  2. Go to the main page
  3. Scroll to the bottom.

## Specifications

  - GmodStore version (see footer): 7.1.53
  - Example url: https://www.gmodstore.com/
  - Browser: Chrome stable
  - Event ID: -

**Comment by b4u7** [comment]
Fixed in v11.0.0
