### ISSUE TITLE
Show when a API key was last used.

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/gmodstore-issues#946]
## Describe a feature you would like to have added to GmodStore
Show when an API key was last used, like GitHub's, so old keys can be revoked.

## Related attachments
![GitHub PATs](https://user-images.githubusercontent.com/32164094/99902660-56184300-2cb7-11eb-95f7-1d6c7462cb30.png)

**Comment by Marcuzz** [comment]
We've had this since API v3
