### ISSUE TITLE
Last downloaded does not update correctly

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/gmodstore-issues#948]
## Expected Behavior
Last download should update

## Actual Behavior
Does not update

## Steps to Reproduce the Problem
https://www.gmodstore.com/dashboard/addons/dan-s-weapon-shelves-sell-weapons-the-right-way/purchases/76561198116888982
Shows he's never updated the addon basically

While the event log tells a different story https://www.gmodstore.com/users/76561198116888982/events?type=addon_download&search=

It actually shows correctly in the "Purchases" tab
![billede](https://user-images.githubusercontent.com/4314483/101156297-ae8d0000-3628-11eb-9d30-9c2956eb305d.png)

While when you click "More info" to show the transaction information, it doesn't.
![billede](https://user-images.githubusercontent.com/4314483/101156334-be0c4900-3628-11eb-9717-69ab4929d55b.png)

## Specifications

  - GmodStore version (see footer): v8.0.0
  - Browser: Firefox

**Comment by Marcuzz** [comment]
Fixed in the next milestone
