### ISSUE TITLE
GMS Roadmap page doesn't pull from GitHub milestones.

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/gmodstore-issues#951]
## Expected Behaviour
GMS Roadmap shows 8.2 and 8.3 milestone.

## Actual Behaviour
GMS Roadmap shows "Woah! There are currently no milestones. Check back soon!"

## Steps to Reproduce the Problem

  1. Go to https://www.gmodstore.com/about/roadmap

## Specifications

  - GmodStore version (see footer): 8.1.1
  - Example url: https://www.gmodstore.com/about/roadmap
  - Browser: Chrome
  - Event ID: -

**Comment by TheodoorP** [comment]
For those interested in what we're currently working on for Gmodstore, you can already view all the previous and upcoming milestones [on this page](https://github.com/everyday-as/gmodstore-issues/milestones).

**Comment by Marcuzz** [comment]
Done in 8.3
