### ISSUE TITLE
Dropdown dupe

### ISSUE THREAD

**Issue by FoksVHox** [everyday-as/gmodstore-issues#957]
## Expected Behavior
To not show two dropdowns

## Actual Behavior
![image](https://user-images.githubusercontent.com/37844753/101341720-cd3a0380-3881-11eb-9861-8ca34b86da2e.png)

## Steps to Reproduce the Problem

  1. Hover community
  2. Then move the cursor closer to the about dropdown

## Specifications

  - GmodStore version (see footer): 8.2.2
  - Example URL: https://www.gmodstore.com/jobmarket/jobs/38174
  - Browser: Brave
  - Event ID: N/A

**Comment by Marcuzz** [comment]
Fixed in 8.3
