### ISSUE TITLE
Collapsible Addon Description Sections

### ISSUE THREAD

**Issue by WilliamVenner** [everyday-as/gmodstore-issues#960]
## Describe a feature you would like to have added to GmodStore

Customer feedback:

https://www.gmodstore.com/market/view/billys-keypads

_"The description is overwhelming"_

### Solution

Addon Description Sections.

Creators can "sectionize" the addon description, splitting it into multiple description boxes.

Each section can have a title and contents.

Each section can be dragged to be sorted on the creator's addon dashboard.

Each section can be marked as collapsible, and also marked as collapsed by default.

### Extra Features

**Header anchoring:** As the user scrolls, the visible header will stick to the top of their viewport, allowing them to collapse the section whenever they want during scrolling.

**Comment by Marcuzz** [comment]
Moving this back to 8.4 unfortunately as we're out of time for the 8.3 milestone

**Comment by WilliamVenner** [comment]
Don't worry dark theme high priority

**Comment by Marcuzz** [comment]
Thought I'd comment to at least show we've started:

![image](https://user-images.githubusercontent.com/3168421/103155432-31285b80-47a0-11eb-8f17-8d213251b59d.png)

**Comment by WilliamVenner** [comment]
That looks way better than what I even imagined :D

**Comment by FoksVHox** [comment]
That's amazing

> Thought I'd comment to at least show we've started:
> 
> ![image](https://user-images.githubusercontent.com/3168421/103155432-31285b80-47a0-11eb-8f17-8d213251b59d.png)

**Comment by Marcuzz** [comment]
Here's some more progress:


https://user-images.githubusercontent.com/3168421/103157125-21187800-47b0-11eb-8b9f-48ec911f985e.mp4
