### ISSUE TITLE
Unable to view own hidden threads

### ISSUE THREAD

**Issue by kanalumaddela** [everyday-as/gmodstore-issues#961]
## Expected Behavior
I can view my own threads irrelevant of whether or not they are hidden per the info notice that shows on the page :/
![image](https://user-images.githubusercontent.com/14265751/101698181-138c8f80-3a47-11eb-88c1-3c1084afc6e1.png)

## Actual Behavior
I get a 403, thanks @J0sh0nat0r 

## Steps to Reproduce the Problem

  1. Be me
  2. https://www.gmodstore.com/users/kanalumaddela/threads
  2. https://www.gmodstore.com/community/threads/6637
  3. 403

## Specifications

  - GmodStore version (see footer): v8.2.11
  - Example url: https://www.gmodstore.com/users/kanalumaddela/threads
  - Browser: Chrome 87.0.4280.88 (Official Build) (64-bit)
  - Event ID: N/A

**Comment by Marcuzz** [comment]
Thanks for including links to both your user profile and the ticket in question.

Fixed in 9.3 😄
