### ISSUE TITLE
Display VAT inclusive prices somewhere in addons settings

### ISSUE THREAD

**Issue by Evans-Developer** [everyday-as/gmodstore-issues#963]
## Describe a feature you would like to have added to GmodStore
When editing an addons price, add a selection box to select a country and it will display the price in the said country including additional costs such as VAT.

Not sure if everyone would agree but considering it says `What the customer will pay`, I think it will be useful to see what the customer will actually pay for your script including VAT costs. Also not urgent because I could just get a calculator out but I'm lazy

**Comment by TheodoorP** [comment]
This isn't something we're interested in adding, mostly as every single country has a different VAT percentage which would basically make it a useless feature. To name a few France has 20% VAT, the Netherlands 21% and Norway 25%.
