### ISSUE TITLE
Ability to remove license amendments completely.

### ISSUE THREAD

**Issue by Evans-Developer** [everyday-as/gmodstore-issues#964]
## Describe a feature you would like to have added to GmodStore
Ability to remove license amendments from an addon completely. Currently, when you first create the script it is empty but once you save something into the amendments it is impossible to remove them as the field is required.

## Related attachments
https://i.imgur.com/jCsm4bG.png

A simple solution is to just replace the amendments with "None" or "N/A" but would be nice if we could remove it completely.
https://i.imgur.com/ExCsOLN.png

**Comment by Marcuzz** [comment]
Fixed in the next version :)
