### ISSUE TITLE
Hard to see 'solved' status badge

### ISSUE THREAD

**Issue by FoksVHox** [everyday-as/gmodstore-issues#967]
## Expected Behavior
That the status badge would have another color

## Actual Behavior
The status badge is dark, and dark mode makes it impossible to see the status badge
![image](https://user-images.githubusercontent.com/37844753/102067777-e26fde80-3dfb-11eb-8568-9c5ec22ef285.png)

## Steps to Reproduce the Problem

  1. Go on a ticket that's is solved with an addon
 

## Specifications

  - GmodStore version (see footer):8.3.2
  - Example URL: https://www.gmodstore.com/dashboard/tickets/157977
  - Browser: Brave
  - Event ID: N/A

**Comment by Marcuzz** [comment]
Fixed in the next release. It's now a success colour as it is inherently a good state. 

The 'open' badge has now been swapped from a success colour to our 'secondary' colour. No badge uses the dark variant anymore.
