### ISSUE TITLE
Colors from icons 

### ISSUE THREAD

**Issue by FoksVHox** [everyday-as/gmodstore-issues#968]
## Expected Behavior
That the colors wouldn't be grayed out as they do now

## Actual Behavior
![image](https://user-images.githubusercontent.com/37844753/102068375-a6894900-3dfc-11eb-8298-9fdb750eb0da.png)

## Steps to Reproduce the Problem

  1. Hover over a dropdown option
  2. See the colors disappears 
  3. 

## Specifications

  - GmodStore version (see footer): 8.3.2
  - Example URL: https://www.gmodstore.com/
  - Browser: Brave
  - Event ID:

**Comment by TheodoorP** [comment]
This is intended behavior. 

Previously it would grey out the drop-down option you were hovering on, which doesn't make much sense.

**Comment by FoksVHox** [comment]
> This is intended behavior.
> 
> Previously it would grey out the drop-down option you were hovering on, which doesn't make much sense.

Alright
