### ISSUE TITLE
Dark theme improvements

### ISSUE THREAD

**Issue by GlorifiedPig** [everyday-as/gmodstore-issues#969]
Dark theme improvements
-
The dark theme in my opinion is not contrasted enough. Here are my colour suggestions:

To start off, the text colours are inconsistent. Some text is white, whilst the rest feels like it's halfway to matching the dark background colour. Contrast is good, but so is consistency. So I believe that the text colour should be matched, and be a light grey (not a full white or a dark grey, because it's not well contrasted and inconsistent):
![image](https://user-images.githubusercontent.com/7416288/102081578-22918a00-3e19-11eb-8601-9592f213db7c.png)

Some buttons are blue, while a lot of other buttons are red. There should be a global option to change all button colours for events, since it looks inconsistent having essentially "opposite" colours everywhere on the same page:
![image](https://user-images.githubusercontent.com/7416288/102081801-7d2ae600-3e19-11eb-89ad-d8d7394e33ef.png)

Adding onto the first point, some text is dark grey, some text is full white, and other text is red. If there should be differences, perhaps it should be in a lower or higher shade of grey, but it feels like there's three completely different colours in all the texts:
![image](https://user-images.githubusercontent.com/7416288/102081934-ba8f7380-3e19-11eb-99fc-f86c5d0b5d29.png)

**Comment by ruigouveiamaciel** [comment]
I think you should keep the colors but make them less saturated, here's an example of saturated vs unsaturated:

Saturated (bad)
![saturated image](https://user-images.githubusercontent.com/17518628/102082291-9d52a900-3e09-11eb-9884-19d4e12eabfb.png)

Desaturated (good)
![less saturated image](https://lh3.googleusercontent.com/mG8uCM_L25hH9PBTG3S_dBBz7mGhauiCshcmZ0jr1laLs42bwRsAjwTj0OBVpSF0aCWRieA-c-QzG9TKm26DWH2cyOyymqptw6P4=w1064-v0)


As google says in its dark theme guidelines "Avoid using saturated colors that visually vibrate against a dark background."

**Comment by Marcuzz** [comment]
Thanks guys, input is highly appreciated! We released the dark theme a bit quickly in order to get useful feedback like this 😄

**Comment by FoksVHox** [comment]
This is also related to #967

**Comment by GlorifiedPig** [comment]
The code blocks also have bad colour contrast:
![image](https://user-images.githubusercontent.com/7416288/102721523-fa67c680-4303-11eb-8758-cb0cd97d4f31.png)

**Comment by Aevoaa** [comment]
The same goes for the DRM Notification
![crDv6ZL](https://user-images.githubusercontent.com/63224213/102818447-eab6b380-43d1-11eb-8d1a-b55d757c8e35.png)
Feel like a Slightly brighter Color like #FFA500 would look a lot better
![JUoqRxG](https://user-images.githubusercontent.com/63224213/102818624-4e40e100-43d2-11eb-891c-be81a0d450b8.png)

**Comment by Crap-Head** [comment]
![billede](https://user-images.githubusercontent.com/4314483/103131686-05bf4700-46a2-11eb-8e08-4a8c91c0aa0c.png)
Hard to read the blue text on blue background

**Comment by TheodoorP** [comment]
Some edits have been made in the last few weeks that should fix some, if not all, of the issues mentioned. If you've got any new feedback please let us know!

**Comment by Marcuzz** [comment]
Closing for now as this issue is too general, and many fixes have been made since^
