### ISSUE TITLE
OGP in Discord doesn't properly render when using addon slug vs addon id.

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/gmodstore-issues#971]
## Expected Behavior
![image](https://user-images.githubusercontent.com/32164094/102354640-c2c6ea80-3fa2-11eb-9930-a0b4379d672d.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/32164094/102354651-c65a7180-3fa2-11eb-8e8f-9d1baa8d2c73.png)

## Steps to Reproduce the Problem

  1. Post slugged addon to discord.
  2. Await embed.

## Specifications

  - GmodStore version (see footer): 8.3.7
  - Example url: https://www.gmodstore.com/market/view/voidcases-unboxing-system / https://www.gmodstore.com/market/view/6922

**Comment by TheodoorP** [comment]
I'm unable to replicate this now, are you able to find any working example?
See:
![image](https://user-images.githubusercontent.com/17050455/103441488-ab4c5a80-4c4e-11eb-8f06-4800f0fd300d.png)

**Comment by JoshPiper** [comment]
Nope, that was the latest example I saw. Unsure if it was an issue with Discord or GMS which was fixed, or what-have-you.
Closed, no-repro.
