### ISSUE TITLE
Delete .git folder when uploading versions

### ISSUE THREAD

**Issue by WilliamVenner** [everyday-as/gmodstore-issues#974]
This could save someone's ass

**Comment by Marcuzz** [comment]
Done. Please let me know if there are any other directories you can think of that should be excluded 👍

**Comment by FoksVHox** [comment]
> Done. Please let me know if there are any other directories you can think of that should be excluded 👍

I assume this would be for when you manually are uploading a version?

**Comment by Marcuzz** [comment]
It's for anything. It's done on download and not on upload 🙂
