### ISSUE TITLE
Automatically close inactive site tickets and reports

### ISSUE THREAD

**Issue by Crap-Head** [everyday-as/gmodstore-issues#976]
## Describe a feature you would like to have added to GmodStore
Hey,

So similar to the function that developers can enable to close inactive tickets after x days, it would be super if site tickets and reports had the same functionality.

Hardcode an amount of days you find suited (maybe 31 days?) and automatically close those inactive tickets if the user doesn't reply. Let the bot user leave a reply that it has been closed for inactivity.

That way, I won't have to go through 3 pages of tickets and reports and close them for inactivity.

**Comment by Marcuzz** [comment]
Done in next release.

Threshold will be 14 days.
