### ISSUE TITLE
Display warning when creating a ticket if a new version is available

### ISSUE THREAD

**Issue by CupCakeR** [everyday-as/gmodstore-issues#977]
## Describe a feature you would like to have added to GmodStore
As an addition to https://github.com/everyday-as/gmodstore-issues/issues/641, I'd like users to be more aware of the fact that a new version might've already fixed an issue they are about to report. A lot of users seem to ignore (?) or simply dismiss their notifications.

## Related attachments
https://i.imgur.com/iKBxt4v.png (one of many other examples)

**Comment by Marcuzz** [comment]
Done in the next release, but to keep the feature in-line with #641 and #1264 we are displaying it to the user _after_ ticket creation.
