### ISSUE TITLE
Filter Tickets by Labels

### ISSUE THREAD

**Issue by LivacoNew** [everyday-as/gmodstore-issues#978]
## Describe a feature you would like to have added to GmodStore
As one of the few people that use ticket labels on gmodstore (to my knowledge), would be cool if I could filter tickets by labels. 
Since labels are based on addons and are not globally set, maybe have a list of addons and their labels, and then once you select a label it filters that label and addon. Either that, or just make labels global while your at it ;)

## Related attachments
N/A

**Comment by Marcuzz** [comment]
For now I think this is the best solution:

![image](https://user-images.githubusercontent.com/3168421/126652735-8c023f26-c243-497a-8be6-1a3df63a6c0c.png)

It will be in this milestone.
