### ISSUE TITLE
Unable to enable push notifications

### ISSUE THREAD

**Issue by FoksVHox** [everyday-as/gmodstore-issues#980]
## Expected Behavior
That I can press the button that says "Enable push notifications", and it'll enable them.

## Actual Behavior
When I press the button it turns into a darker shade of blue, and the back to normal blue.

## Steps to Reproduce the Problem

  1.  Go to https://www.gmodstore.com/notifications
  2. Press "Enable Push notifications"

## Specifications

  - GmodStore version (see footer): 8.3.41
  - Example URL: https://www.gmodstore.com/notifications
  - Browser: Brave
  - Event ID: N/A

**Comment by TheodoorP** [comment]
This is due to a new Brave privacy setting, please enable the follow to fix your push notifications:
![image](https://user-images.githubusercontent.com/17050455/103948919-e3660880-513a-11eb-90ff-7c5b189d3ac6.png)

**Comment by FoksVHox** [comment]
> This is due to a new Brave privacy setting, please enable the follow to fix your push notifications:
> ![image](https://user-images.githubusercontent.com/17050455/103948919-e3660880-513a-11eb-90ff-7c5b189d3ac6.png)

I'm able to use push notifications on other sites?

**Comment by TheodoorP** [comment]
> 
> 
> > This is due to a new Brave privacy setting, please enable the follow to fix your push notifications:
> > ![image](https://user-images.githubusercontent.com/17050455/103948919-e3660880-513a-11eb-90ff-7c5b189d3ac6.png)
> 
> I'm able to use push notifications on other sites?

It is a brave issue as can be read here: https://github.com/brave/brave-browser/issues/2301#issuecomment-568440814
