### ISSUE TITLE
Create a carousel for addons on the main page

### ISSUE THREAD

**Issue by Fleodon** [everyday-as/gmodstore-issues#981]
## Describe a feature you would like to have added to GmodStore
Hey,
I want to suggest a carousel system, it will be added on the following sections:
- **Popular addons:** We can imagine two or three sheets for the carousel.
- **Newcomers addons:** Like the previous section, you could add two or three sheets.

Thanks to this idea, customers might discover new addons than those which are already on the main page. And, content creators may probably have more views/purchases.

## Related attachments
Here is an example to show you where the right arrow could be added:
![proof1](https://user-images.githubusercontent.com/36356299/104226406-0a2c8380-5448-11eb-9784-c3f985ef85c4.jpg)
![proof2](https://user-images.githubusercontent.com/36356299/104226424-1284be80-5448-11eb-82ab-6e10ed861f01.jpg)

**Comment by TheodoorP** [comment]
We're not interested in adding this at this time
