### ISSUE TITLE
Indecisive timestamps

### ISSUE THREAD

**Issue by cl3dev** [everyday-as/gmodstore-issues#986]
## Expected Behavior
Time of creation is shown

## Actual Behavior
Timestamp has a party and changes constantly
![Example](https://i.imgur.com/b0FOP0Y.gif)
## Steps to Reproduce the Problem

  1. Load any page with timestamps (forums, jobs etc)

## Specifications

  - GmodStore version (see footer): 8.3.45
  - Example url: https://www.gmodstore.com/jobmarket/jobs/browse
  - Browser: Firefox 85.0 (64-bit)
  - Event ID:

**Comment by Marcuzz** [comment]
I'm unable to replicate this bug in any evergreen browser, I'm using Firefox as a daily driver and I have never seen this occur.

Did you leave the browser on the same page over a computer sleep cycle or something?

**Comment by cl3dev** [comment]
> 
> 
> I'm unable to replicate this bug in any evergreen browser, I'm using Firefox as a daily driver and I have never seen this occur.
> 
> Did you leave the browser on the same page over a computer sleep cycle or something?

Nope, it's persistent throughout every visit and I also tried in the private browser to avoid any extensions that might be causing it and I still have the issue. It must be something clientside so don't worry about it.
