### ISSUE TITLE
Issuing a refund succeeds but redirects to 401

### ISSUE THREAD

**Issue by realSaddy** [everyday-as/gmodstore-issues#989]
## Expected Behavior
When issuing a refund to a customer via the purchase page, assuming it succeeds, it should refresh the page or show the updated information.

## Actual Behavior
When I issued a refund this last time, I was redirected to a 401 error page, but the refund request still went through successfully. I don't have any way to repeat this myself at the moment, but figured I should report it.

## Steps to Reproduce the Problem

  1. Have a user purchase an addon.
  2. Issue a refund for the purchase on the Purchases page.

## Specifications

  - GmodStore version (see footer): v8.3.45	
  - Example url: N/A
  - Browser: GNU/Linux Ungoogled Chromium 87.0.4280.88
  - Event ID: Didn't manage to grab it, sorry!

**Comment by TheodoorP** [comment]
Will fixed in 8.4
