### ISSUE TITLE
API rate limiting rate limits by IP address, not API key

### ISSUE THREAD

**Issue by WilliamVenner** [everyday-as/gmodstore-issues#990]
## Expected Behavior
Get rate limited, switch API key, no longer be rate limited.

Get rate limited, switch machine/IP address, still rate limited.

## Actual Behavior
Get rate limited, switch API key, still rate limited.

Get rate limited, switch machine/IP address, no longer be rate limited.

## Steps to Reproduce the Problem

```bash
npm install gmodstore-sdk --save
node
```

```js
const GmodStoreSdk = require('gmodstore-sdk');
const GmodStoreHTTPClient = GmodStoreSdk.ApiClient.instance;
GmodStoreHTTPClient.authentications['bearerAuth'].accessToken = 'API_KEY_HERE';
const GmodStoreUsers = new GmodStoreSdk.UsersApi();

for (let i = 0; i < 65; i++) GmodStoreUsers.getSelfUser();
```

## Specifications

  - GmodStore version (see footer): v8.3.45
  - Example url: N/A
  - Browser: N/A
  - Event ID: N/A

**Comment by TheodoorP** [comment]
API v3 will rate limit by user on authenticated requests, and by IP address on unauthenticated requests.
