### ISSUE TITLE
Remove capital letters and special characters from GitHub auto deployments

### ISSUE THREAD

**Issue by GlorifiedPig** [everyday-as/gmodstore-issues#991]
Please remove capital letters & special characters from the auto deployments - I keep getting extra random support tickets saying the addon isn't loading because people don't know they should be naming the script folder something simple

**Comment by Marcuzz** [comment]
Hey,

Do you have an example for us, like a link to an addon we can download?

**Comment by GlorifiedPig** [comment]
https://www.gmodstore.com/market/view/glorifiedbanking

Here you go

**Comment by Marcuzz** [comment]
Fixed in next release (will only take effect for new deployments)
