### ISSUE TITLE
Roadmap isn't ordered properly

### ISSUE THREAD

**Issue by TheodoorP** [everyday-as/gmodstore-issues#993]
## Expected Behavior
Future versions on the roadmap should be ordered by name ascending

## Actual Behavior
They're currently ordered randomly, see:
![image](https://user-images.githubusercontent.com/17050455/109567235-5493bd80-7ae5-11eb-93a0-6193d9e8bf01.png)

## Specifications

  - GmodStore version (see footer):	V8.3.49
  - Example url: [https://www.gmodstore.com/about/roadmap](https://www.gmodstore.com/about/roadmap)
  - Browser:
  - Event ID:

**Comment by Marcuzz** [comment]
Fixed in next release
