### ISSUE TITLE
Roadmap Sort Order

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/gmodstore-issues#997]
## Expected Behavior
Roadmap sorts in semantic order, 8.4, 8.5, 8.6

## Actual Behavior
8.4, 8.6, 8.5

## Steps to Reproduce the Problem

  1. Go to page
  2. Use eyes

## Specifications

  - GmodStore V: 8.3.49
  - Example URL: https://www.gmodstore.com/about/roadmap
  - Browser: Chrome

**Comment by TheodoorP** [comment]
Duplicate of #993
