### ISSUE TITLE
Don't lose input when validation fails

### ISSUE THREAD

**Issue by TheodoorP** [everyday-as/gmodstore-issues#998]
## Describe a feature you would like to have added to GmodStore
Currently, when submitting a form which fails validation, all the inputted data will not be retained. This causes some unnecessary anger:
 ![An example of some anger](https://storage.googleapis.com/theodoordev.appspot.com/02a8a11d5015442)

At least form fields with a max body size greater than 1000 characters should retain the old input, but ideally most if not all inputs should do this.

**Comment by Marcuzz** [comment]
Which form does this happen in?

The user should not be allowed to submit anything if validation fails.

**Comment by Marcuzz** [comment]
The area in question no longer does this
